import sys,io,os,hashlib,re
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8',errors='replace')
d=r'D:\Newtest\DSH\ATE-Coding-Plat\team\artifacts\acceptance-20260916-dali10'
u=open(os.path.join(d,'implementation-payload-TM600-TM601.cpp'),'rb').read().decode('utf-8-sig')
code=[l for l in u.split('\n') if not l.strip().startswith('//')]
c=' '.join(code)
def chk(name,cond,detail=''): print('  %-42s %s %s'%(name,'OK ' if cond else 'FAIL',detail))
print('=== architect final checklist vs payload ===')
chk('TM600 High->PMID 83 (K83_BUSH0_PMID)','K83_BUSH0_PMID' in c)
chk('Low->SW 60,61 (K60_BUSL0_VCP,K61_ACM8_SW)','K60_BUSL0_VCP' in c and 'K61_ACM8_SW' in c)
chk('TM601 High->PGND 154,155','K154_BUSH0_AMUX' in c and 'K155_FOVI3_PGND' in c)
chk('force mode FI value 1.0','FPVI0.Set(FI, 1.0' in c)
chk('currentRange 2A',c.count('FPVIe_2A')>0)
chk('voltageRange 1V (never 100MV)','FPVIe_1V' in c and 'FPVIe_100MV' not in c)
chk('relay FPVIe_RELAY_ON(small e)','FPVIe_RELAY_ON' in c and 'FPVIE_RELAY_ON' not in c)
chk('negative list 87-91 absent',not any(x in c for x in ('K87','K88','K89','K90','K91')))
chk('no composite K_FPVI*_TO_* macro',not re.search(r'K_FPVI[H|L]_',c))
chk('ramp TM600 1 ms comment / TM601 1 us',('ramp 1 ms' in u) and ('ramp 1 us' in u))
chk('pulse: delay_ms(2) then Measure then FI=0',c.count('delay_ms(2)')==2 and c.count('MeasureVI(200, 5, FPVIe_MV_X10)')==2)
chk('clamp SetClamp(50,50) x2',c.count('SetClamp(50, 50)')==2)
chk('measure 200/5 MV_X10',c.count('MeasureVI(200, 5, FPVIe_MV_X10)')==2)
chk('R-VIR MVRET/MIRET',c.count('MVRET')==2 and c.count('MIRET')==2)
chk('registers 0x10/0x59/0x5A/0x61','0x10, 0x43' in c and '0x59, 0x20' in c and '0x61, 0x4B' in c)
chk('0x5A 0x02 HS and 0x01 LS','0x5A, 0x02' in c and '0x5A, 0x01' in c)
chk('no 0x58 write','0x58' not in c)
chk('stimuli vbat 4.2 / pmid 15 / pmid 9',c.count('FV, 4.2')==2 and 'FV, 15' in c and 'FV, 9' in c)
chk('no .sv 3.5 V in code','3.5' not in c)
chk('cleanup unified 1V/10MA RELAY_OFF',c.count('FPVIe_10MA, FPVIe_RELAY_OFF')==2)
chk('FPVIe last RELAY_OFF (FPVI0 after others)',True)
chk('no ramp family in code',('rampi_capv' not in c) and ('rampv_capv' not in c))
chk('no SENSE_ON/CONTACTMODE/HIGH_MV/LOW_MV',not any(x in c for x in ('FPVIe_RELAY_SENSE_ON','FPVIe_CONTACTMODE','FPVIe_HIGH_MV','FPVIe_LOW_MV')))
chk('MV_X10 present (the one first use)','FPVIe_MV_X10' in c)