import sys,io,os,re
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8',errors='replace')
sd=r'D:\Newtest\DSH\ATE-Coding-Plat\scripts'
l=open(os.path.join(sd,'verify_bst_sw_sequence.py'),encoding='utf-8-sig').read().split('\n')[146]
print('L147 = %s'%l)
print()
print('=== THEIR CLAIM: "len" does NOT occur in this line; my claim that it hides in "label" is FALSE ===')
print('  "len" in line        :', 'len' in l)
print('  "len" in "label"     :', 'len' in 'label')
print('  "label" in line      :', 'label' in l)
print('  => my stated cause is', 'CORRECT' if 'len' in 'label' else 'FALSE')
print()
print('=== then WHY did my broad predicate flag it? reproduce the predicate ===')
print('  my broad scan required: (something like ")" then "-") AND ("len(" or "count(" or "sum(" in line)')
print('  ")" + "-" present as "->"?', bool(re.search(r'\)\s*-\s*',l)))
print('  "->" actually contains "-" yes; and the ")" before it is the arg list close')
m=re.search(r'\)\s*-\s*',l)
print('  match:', repr(m.group(0)) if m else None)
print('  "count(" in line?', 'count(' in l, '| "len(" in line?', 'len(' in l, '| "sum(" in line?', 'sum(' in l)
print()
print('=== so which sub-condition failed to be true? ===')
print('  require_exact_count(  contains "count" but the literal "count(" is: %s'%('count(' in l))
print('  and the "-" comes from: %s'%repr(l[l.find('->')-1:l.find('->')+2]))
print()
print('=== and their anchoring fix: does \\bcount\\( avoid this line? ===')
print('  re.search(r"\\bcount\\s*\\(", label_text):', bool(re.search(r'\bcount\s*\(','require_exact_count(')))
print('  re.search(r"\\bcount\\s*\\(", real call "count(token)"):', bool(re.search(r'\bcount\s*\(','x.count(token)')))