import sys,io,os,re,hashlib,json
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8',errors='replace')
d=r'D:\Newtest\DSH\ATE-Coding-Plat\team\artifacts\acceptance-20260916-dali10'
# final acceptance evidence
p=os.path.join(d,'implementation-payload-TM600-TM601.cpp')
r=open(p,'rb').read(); u=r.decode('utf-8-sig'); c=re.sub(r'//.*$','',u,flags=re.M)
print('=== t23 acceptance matrix (live, one pass) ===')
print('payload            %d B / %s'%(len(r),hashlib.sha256(r).hexdigest()))
print('BOM=%s loneLF=%d'%(r[:3]==b'\xef\xbb\xbf',r.count(b'\n')-r.count(b'\r\n')))
print('delay_ms(1)        ',c.count('delay_ms(1)'))
print('delay_ms(2)        ',c.count('delay_ms(2)'))
print('SetClamp(50, 50)   ',c.count('SetClamp(50, 50)'))
print('MeasureVI(200,5,X10)',c.count('MeasureVI(200, 5, FPVIe_MV_X10)'))
print('rampi/rampv_capv   ',c.count('rampi_capv')+c.count('rampv_capv'))
print('K5_VBUS_Cap        ',c.count('K5_VBUS_Cap'))
print('K44_Cap_SW2_BST2   ',c.count('K44_Cap_SW2_BST2'))
print('K45_Cap_SW1_BST1   ',c.count('K45_Cap_SW1_BST1'))
print('K57_CAP_BST_SW     ',c.count('K57_CAP_BST_SW'))
print('K126_V1P5_CAP      ',c.count('K126_V1P5_CAP'))
print('bare 126 tokens    ',len(re.findall(r'(?<![\dA-Za-z_])126(?![\dA-Za-z_])',c)))
print('ERROR_RES          ',c.count('ERROR_RES'))
print('inert phrasing     ',u.count('inert for the measurement'))
print('SETTLING caveat    ',u.count('SETTLING IS NOT ANALYSED'))
print('TM643 mentions     ',u.count('TM643'))
print('TM601 SetOn        ',re.findall(r'cbite\.SetOn\((K154[^;]*)\);',u)[0][:150])
print()
a=os.path.join(d,'APPLY-TM600-TM601.md'); ra=open(a,'rb').read()
print('APPLY doc %d B / %s'%(len(ra),hashlib.sha256(ra).hexdigest()))
mf=os.path.join(d,'implementation-manifest.json')
print('implementation-manifest.json exists:',os.path.exists(mf))
s=open(r'D:\PROJECT6-DALI\ForCodexDebug\source\test.cpp','rb').read()
print('target: %d B / %s (unchanged=%s)'%(len(s),hashlib.sha256(s).hexdigest(),hashlib.sha256(s).hexdigest()=='3dbceb496d79d7d08631713b98e46c0c2ba6163eaf5356a87dded677e35ba479'))