import sys,io,os,hashlib,time,re
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8',errors='replace')
d=r'D:\Newtest\DSH\ATE-Coding-Plat\team\artifacts\acceptance-20260916-dali10'
b=os.path.join(d,'backups')
print('=== 1) WHERE MY SCRATCH & README CAME FROM (the real provenance story) ===')
mine_before=os.path.exists(os.path.join(d,'backups'))
sub=os.path.join(b,'superseded-scratch')
print('  superseded-scratch/ still absent:', not os.path.exists(sub))
rp=os.path.join(b,'README-READ-BEFORE-RUNNING.md')
r=open(rp,'rb').read()
print('  README: %d B / %s'%(len(r),hashlib.sha256(r).hexdigest()))
print('  authored by me (content check):', 'ate-implementer' in r.decode('utf-8'))
print()
print('=== 2) THE ONE REMAINING DISCREPANCY THEY AND I BOTH MEASURE DIFFERENTLY ===')
t=open(os.path.join(d,'review-handoff-note-plan-side.md'),'rb').read().decode('utf-8-sig')
print('  note now: %d B / %s'%(len(open(os.path.join(d,'review-handoff-note-plan-side.md'),'rb').read()),hashlib.sha256(open(os.path.join(d,'review-handoff-note-plan-side.md'),'rb').read()).hexdigest()))
print('  "is to become" = %d  (was the forward-looking wrong-target phrase)'%t.count('is to become'))
for i,l in enumerate(t.split('\n')):
    if 'is to become' in l: print('    L%d: %s'%(i+1,l.strip()[:150]))
print()
print('=== 3) FINAL CROSS-CHECK OF MY OWN DELIVERY (the thing that actually matters) ===')
p=os.path.join(d,'implementation-payload-TM600-TM601.cpp'); pr=open(p,'rb').read()
code=re.sub(r'//.*$','',pr.decode('utf-8-sig'),flags=re.M)
print('  payload: %d B / %s @%s'%(len(pr),hashlib.sha256(pr).hexdigest(),time.strftime('%H:%M:%S',time.localtime(os.stat(p).st_mtime))))
print('  frozen canonical 66abc088...:', hashlib.sha256(pr).hexdigest()=='66abc088ae6bd5f9b9d7201673003fc0be2450fd6f1f222c6a4a902cbe4f0cc4')
print('  executable: K48=%d K76=%d K109=%d K110=%d K46=%d'%(code.count('K48_ACM5_AMP_REF'),code.count('K76_ACM_BST'),code.count('K109_BUSL1_PB0'),code.count('K110_ACM18_BST'),code.count('K46')))
print('  BOM:',pr[:3]==b'\xef\xbb\xbf','| loneLF:',pr.count(b'\n')-pr.count(b'\r\n'))