import sys,io,os,hashlib,time
sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8',errors='replace')
d=r'D:\Newtest\DSH\ATE-Coding-Plat\team\artifacts\acceptance-20260916-dali10'
n=os.path.join(d,'review-handoff-note-plan-side.md')
r=open(n,'rb').read(); t=r.decode('utf-8-sig'); L=t.split('\n'); h=hashlib.sha256(r).hexdigest()
print('=== their new anchor ===')
print('  %d B / %s @%s'%(len(r),h,time.strftime('%H:%M:%S',time.localtime(os.stat(n).st_mtime))))
print('  they cite 74,541 B / 1ed5c1da56e150053e0f45a994e87d3c026954b8394eeb32a3628b6e9084646c @23:28:27')
print('  match:', h=='1ed5c1da56e150053e0f45a994e87d3c026954b8394eeb32a3628b6e9084646c')
print()
print('=== did they adopt the "verify the claim, not the line" clause? ===')
print('  "claim is absent" count:', t.count('claim is absent'))
print('  "verify the claim" count:', t.count('verify the claim'))
print()
print('=== and the two annotation items I flagged: still present? (I am not re-raising, just recording) ===')
print('  "exactly once, here" count:', t.count('exactly once, here'))
print('  "is to become" count:', t.count('is to become'))
print()
print('=== my delivery, verified once more ===')
p=os.path.join(d,'implementation-payload-TM600-TM601.cpp'); pr=open(p,'rb').read()
import re
code=re.sub(r'//.*$','',pr.decode('utf-8-sig'),flags=re.M)
print('  payload %d B / %s @%s'%(len(pr),hashlib.sha256(pr).hexdigest(),time.strftime('%H:%M:%S',time.localtime(os.stat(p).st_mtime))))
print('  BOM:%s loneLF:%d CRLF:%d'%(pr[:3]==b'\xef\xbb\xbf',pr.count(b'\n')-pr.count(b'\r\n'),pr.count(b'\r\n')))
print('  K48=%d K76=%d K109=%d K110=%d K46=%d'%(code.count('K48_ACM5_AMP_REF'),code.count('K76_ACM_BST'),code.count('K109_BUSL1_PB0'),code.count('K110_ACM18_BST'),code.count('K46')))