/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_SS_1 ////////////
// Test Item: BOOST_300, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.swVAC2.set_ron_val(10);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 10¦¸
//		res[vac2,10]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x1E);  // Write reg 0xD = 30
//		field[(VBUS_VOL_SET_L,30),(BUBO_MODE,1),(BUBO_EN,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x04);  // Write reg 0xC = 4
I2CWriteSameData(DEV_ADDR, 0x0D, 0xE6);  // Write reg 0xD = 230
//		field[(VBUS_OVP,1),(VBUS_VOL_SET_L,230)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
//		field[(AC2_GATE_ON,0),(BUBO_EN,0)]
#5000000;  // delay 5e-3s
//		delay[5e-3]

// Error: command format error: nan
//		nan

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////