/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: boost at high voltage ////////////
// Test Item: BOOST_301_2, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x12);  // Write reg 0xC = 18
I2CWriteSameData(DEV_ADDR, 0x0D, 0x76);  // Write reg 0xD = 118
I2CWriteSameData(DEV_ADDR, 0xFF, 0x04);  // Write reg 0xFF = 4
//		field[(MPP_EN,1),(VBUS_OVP,4),(VBUS_VOL_SET_H,2),(VBUS_VOL_SET_L,118)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
//		field[(AC2_GATE_ON,1),(BUBO_MODE,1),(BUBO_EN,1)]
#500000;  // delay 500e-6s
//		delay[500e-6]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(16.5, 100e-6);
#1000;
// pin VAC2 set to 16.5V
//		vset[vac2,16.5,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#14000000;  // delay 14e-3s
//		delay[14e-3]
`NVT_STIM.en_vsrc_vac2 = 0;  // disable vac2
//		vset_off[vac2]

`NVT_STIM.swVAC2.set_ron_val(20);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 20¦¸
//		res[vac2,20]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.swVAC2.set_ron_val(50);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 50¦¸
//		res[vac2,50]
#1000000;  // delay 1e-3s
//		delay[1e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////