/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_SS_2 ////////////
// Test Item: BOOST_301, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5.5, 100e-6);
#1000;
// pin VAC2 set to 5.5V
//		vset[vac2,5.5,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x1E);  // Write reg 0xD = 30
//		field[(AC2_GATE_ON,1)£¬(VBUS_VOL_SET_L,30),(BUBO_MODE,1),(BUBO_EN,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Renew reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x3C);  // Renew reg 0xD = 60
//		field_renew[(VBUS_VOL_SET_L,60),(BUBO_MODE,1),(BUBO_EN,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]

// Error: command format error: nan
//		nan

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////