/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_LOOP_TRANS_1 ////////////
// Test Item: BOOST_311, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x1E);  // Write reg 0xD = 30
I2CWriteSameData(DEV_ADDR, 0x0F, 0x06);  // Write reg 0xF = 6
//		field[(VBUS_VOL_SET_L,30),(BUBO_MODE,1),(BUBO_EN,1),(VCLAMP,1),(IR_COMP,2)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.swVAC2.set_ron_val(4);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 4¦¸
//		res[vac2,4]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#1000000;  // delay 1e-3s
//		delay[1e-3]

I2CWriteSameData(DEV_ADDR, 0x0E, 0x25);  // Write reg 0xE = 37
//		field[(IBUS_SET,37)]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.swVAC2.set_ron_val(2);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 2¦¸
//		res[vac2,2]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(IBUS_SET,57)]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.swVAC2.set_ron_val(1);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 1¦¸
//		res[vac2,1]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
//		field[(BUBO_EN,0)]
#2000000;  // delay 2e-3s
//		delay[2e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////