/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: LOAD transent ////////////
// Test Item: BOOST_304_2, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.swVAC2.set_ron_val(20);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 20¦¸
//		res[vac2,20]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x1E);  // Write reg 0xD = 30
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(VBUS_VOL_SET_L,30),(IBUS_SET,57),(BUBO_MODE,1),(BUBO_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.swVAC2.set_ron_val(2);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 2¦¸
//		res[vac2,2]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.swVAC2.set_ron_val(10);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 10¦¸
//		res[vac2,10]
#1000000;  // delay 1e-3s
//		delay[1e-3]

`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
#6000000;  // delay 6e-3s
//		delay[6e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////