/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_BS_PROT_3 ////////////
// Test Item: BOOST_309, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.swVAC2.set_ron_val(10);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 10¦¸
//		res[vac2,10]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
`NVT_STIM.vsrcBST2SW.ramp_vsrc_val(0.1, 1e-6);
`NVT_STIM.en_vsrc_bst2sw = 1;
#1000;
// pin BST2SW set to 0.1V
//		vset[bst2sw,0.1,1e-6,1]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x1E);  // Write reg 0xD = 30
//		field[(VBUS_VOL_SET_L,30),(BUBO_MODE,1),(BUBO_EN,1)]
#6000000;  // delay 6e-3s
//		delay[6e-3]
`NVT_STIM.en_vsrc_bst2sw = 0;  // disable bst2sw
//		vset_off[bst2sw]
#6000000;  // delay 6e-3s
//		delay[6e-3]

// Error: command format error: nan
//		nan

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////