/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_SS_CV ////////////
// Test Item: BUCK_202, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 100e-6);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 0.5e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,0.5e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x01, 0x40);  // Write reg 0x1 = 64
//		field[(VBUS_PRESENT_INT_MASK,0),BUBO_LOOP_INT_MASK,0),(CHG_FSM_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(BUBO_FAULT_INT MASK,0),(VAC_PRESENT_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0)]

I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0A, 0x4D);  // Write reg 0xA = 77
I2CWriteSameData(DEV_ADDR, 0x0B, 0x07);  // Write reg 0xB = 7
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(AC2_GATE_ON,1),(IBUS_SET,57),(VBAT_CV,13),(BUBO_EN,1),(ITERM,7)]
#2500000;  // delay 2.5e-3s
//		delay[2.5e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 2e-3);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,2e-3,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Renew reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Renew reg 0x9 = 6
//		field_renew[(AC2_GATE_ON,1),(BUBO_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
#3000000;  // delay 3e-3s
//		delay[3e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////