/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_SS_TRIKLE ////////////
// Test Item: BUCK_201, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 0.5e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,0.5e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]

//		field[(VBAT_CV,9)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0B, 0x30);  // Write reg 0xB = 48
//		field[(AC2_GATE_ON,1),(ITRIKLE,3),(BUBO_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 1e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
#10000000;  // delay 10e-3s
//		delay[10e-3]

$finish;
//		finish[]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////