/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_SS_CC ////////////
// Test Item: BUCK_200, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 0.5e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,0.5e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x28);  // Write reg 0x8 = 40
//		field[(VAC2_PULLDOWN,1),(VBUS_PULLDOWN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
//		field[(VAC2_PULLDOWN,0),(VBUS_PULLDOWN,0)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(AC2_GATE_ON,1),(IBUS_SET,57),(VBAT_CV,9),(BUBO_EN,1)]
#3000000;  // delay 3e-3s
//		delay[3e-3]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(9, 40e-6);
#1000;
// pin VAC2 set to 9V
//		vset[vac2,9,40e-6,0]
#20000000;  // delay 20e-3s
//		delay[20e-3]

I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Renew reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x0C, 0x04);  // Renew reg 0xC = 4
//		field_renew[(AC2_GATE_ON,1),(VBUS_OVP,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Renew reg 0x9 = 6
//		field_renew[(BUBO_EN,1)]
#4000000;  // delay 4e-3s
//		delay[4e-3]
`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
#2000000;  // delay 2e-3s
//		delay[2e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////