/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_LOOP_TRANS_1 ////////////
// Test Item: BUCK_212, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(4.8, 100e-6);
#1000;
// pin VAC2 set to 4.8V
//		vset[vac2,4.8,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0A, 0x4D);  // Write reg 0xA = 77
I2CWriteSameData(DEV_ADDR, 0x0B, 0x30);  // Write reg 0xB = 48
I2CWriteSameData(DEV_ADDR, 0x0E, 0x25);  // Write reg 0xE = 37
//		field[(AC2_GATE_ON,1),(ITRIKLE,3),(IBUS_SET,37),(VBAT_CV,13),(BUBO_EN,1)]
#4000000;  // delay 4e-3s
//		delay[4e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 2e-3);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,2e-3,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(6, 1e-3);
#1000;
// pin VAC2 set to 6V
//		vset[vac2,6,1e-3,0]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]

I2CWriteSameData(DEV_ADDR, 0x0B, 0x37);  // Write reg 0xB = 55
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(IBUS_SET,57),(ITERM_AUTO_En,1),(ITERM,7)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 2e-3);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,2e-3,0]
#5000000;  // delay 5e-3s
//		delay[5e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////