/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_PROTECT_3 ////////////
// Test Item: BUCK_206, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 0.5e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,0.5e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(AC2_GATE_ON,1),(IBUS_SET,57),(VBAT_CV,9),(BUBO_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 50e-9);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,50e-9,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 500e-9);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,500e-9,0]
#3000000;  // delay 3e-3s
//		delay[3e-3]

$finish;
//		finish[]

// Error: command format error: nan
//		nan

/////////////////////// End of Auto-generated Code ////////////