/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_BS_PROT_2 ////////////
// Test Item: BUCK_209, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

// Unknown command: //vset
//		//vset[vbat,3.7,100e-6,0] (default)
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.60, 100e-6);
#1000;
// pin VBAT set to 4.60V
//		vset[vbat,4.60,100e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(6, 0.5e-6);
#1000;
// pin VAC2 set to 6V
//		vset[vac2,6,0.5e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0A, 0x51);  // Write reg 0xA = 81
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(AC2_GATE_ON,1),(IBUS_SET,57),(VBAT_CV,17),(BUBO_EN,1)]

#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Renew reg 0x8 = 2
//		field_renew[(AC2_GATE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Renew reg 0x9 = 6
//		field_renew[(BUBO_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////