/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VMCU_shipmode4 ////////////
// Test Item: MISC_008, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x08);  // Write reg 0xFF = 8
//		field[(rx_mode_en,1)] // enable rx function
I2CWriteSameData(DEV_ADDR, 0x30, 0x20);  // Write reg 0x30 = 32
//		field[(RX_SW_PING_DET,1)] // enable rx ping det
I2CWriteSameData(DEV_ADDR, 0x33, 0x78);  // Write reg 0x33 = 120
//		field[(RX_SW_PING_DET_QUIT_EN,1)] // enable rx ping quit shipmode
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x29, 0x01);  // Write reg 0x29 = 1
//		field[(shipmode_en,1)]
`NVT_STIM.en_vac1_cable_insert = 0;  // plugout vac1
//		plugout[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VAC1 set to 0V
//		vset[vac1,0,100e-6,0]
#100000000;  // delay 100e-3s
//		delay[100e-3]

`NVT_STIM.en_vsrc_vrect = 1;
`NVT_STIM.vsrcVRECT.ramp_vsrc_val(6, 100e-6);
#1000;
// pin VRECT set to 6V
//		vset[vrect,6,100e-6,0]
`NVT_STIM.reg_en_tx = 1;  // en_reg tx, 1
//		en_reg[tx,1]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 781;
tb.Ipwm.shift = 4687;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 10.0% duty, 10.0% shift
//		pwm_set[128e3,10,10,1]
#100000;  // delay 0.1e-3s
//		delay[0.1e-3]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 781;
tb.Ipwm.shift = 4687;
tb.Ipwm.en = 0;
#1000;
// PWM: 128000.0Hz, 10.0% duty, 10.0% shift
//		pwm_set[128e3,10,10,0]
#100000000;  // delay 100e-3s
//		delay[100e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////