/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VMCU_NQON_1 ////////////
// Test Item: MISC_004, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x29, 0x02);  // Write reg 0x29 = 2
//		field[(vmcu_reset,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.reg_en_nqon_pd = 1;  // pressDown nQON, 1
//		pressDown[nQON,1]
#10000000;  // delay 10e-3s
//		delay[10e-3]
#500000000;  // delay 500e-3s
//		delay[500e-3]
`NVT_STIM.reg_en_nqon_pd = 0;  // pressDown nQON, 0
//		pressDown[nQON,0]
#100000000;  // delay 100e-3s
//		delay[100e-3]

// Error: command format error: nan
//		nan

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////