/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: Normal_Sleep_VBAT ////////////
// Test Item: MISC_001, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x07, 0x06);  // Write reg 0x7 = 6
//		field[(VAC1_APORT_DET_Enable,1),(VAC2_APORT_DET_Enable,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vac1_cable_insert = 0;  // plugout vac1
//		plugout[vac1]

#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x53);  // Write reg 0x10 = 83
//		field[(sw_rst,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Renew reg 0x10 = 67
//		field_renew[(wake_up,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x41);  // Write reg 0x10 = 65
//		field[(wake_up,0)]

#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////