/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: Normal_Sleep_VAC1 ////////////
// Test Item: MISC_002, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vac3_cable_insert = 1;  // plugin vac3
//		plugin[vac3]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC3 set to 5V
//		vset[vac3,5,100e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x01, 0x08);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.reg_en_mcu_load = 1;  // en_reg mcu_load, 1
//		en_reg[mcu_load,1]

I2CWriteSameData(DEV_ADDR, 0x07, 0x06);  // Write reg 0x7 = 6
//		field[(VAC1_APORT_DET_Enable,1),(VAC2_APORT_DET_Enable,1)]
#20000000;  // delay 20e-3s
//		delay[20e-3]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
#20000000;  // delay 20e-3s
//		delay[20e-3]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#20000000;  // delay 20e-3s
//		delay[20e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x51);  // Write reg 0x10 = 81
//		field[(SW_RST,1)]
#20000000;  // delay 20e-3s
//		delay[20e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Renew reg 0x10 = 67
//		field_renew[(wake_up,1)]
#20000000;  // delay 20e-3s
//		delay[20e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x51);  // Renew reg 0x10 = 81
//		field_renew[(SW_RST,1)]
#20000000;  // delay 20e-3s
//		delay[20e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////