/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: AMUX_BAT_ONLY ////////////
// Test Item: MISC_009, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x10);  // Write reg 0x11 = 16
//		field[(amux_en,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x11);  // Write reg 0x11 = 17
//		field[(channel_mux,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x12);  // Write reg 0x11 = 18
//		field[(channel_mux,2)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x13);  // Write reg 0x11 = 19
//		field[(channel_mux,3)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x14);  // Write reg 0x11 = 20
//		field[(channel_mux,4)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x15);  // Write reg 0x11 = 21
//		field[(channel_mux,5)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x16);  // Write reg 0x11 = 22
//		field[(channel_mux,6)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x17);  // Write reg 0x11 = 23
//		field[(channel_mux,7)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x18);  // Write reg 0x11 = 24
//		field[(channel_mux,8)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x19);  // Write reg 0x11 = 25
//		field[(channel_mux,9)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1A);  // Write reg 0x11 = 26
//		field[(channel_mux,10)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1B);  // Write reg 0x11 = 27
//		field[(channel_mux,11)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1C);  // Write reg 0x11 = 28
//		field[(channel_mux,12)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1D);  // Write reg 0x11 = 29
//		field[(channel_mux,13)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1E);  // Write reg 0x11 = 30
//		field[(channel_mux,14)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(channel_mux,15)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////