/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: I2C_RST ////////////
// Test Item: MISC_011, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
force `NVT_STIM.SDA = 0;  // force `NVT_STIM.SDA = 0
//		force[`NVT_STIM.SDA,0]
force `NVT_STIM.SCL = 1;  // force `NVT_STIM.SCL = 1
//		force[`NVT_STIM.SCL,1]
#1000000000;  // delay 1s
//		delay[1]
#1000000000;  // delay 1s
//		delay[1]
#1000000000;  // delay 1s
//		delay[1]

#1000000000;  // delay 1s
//		delay[1]
#1000000000;  // delay 1s
//		delay[1]
#1000000000;  // delay 1s
//		delay[1]
#1000000000;  // delay 1s
//		delay[1]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////