/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VMCU_shipmode3 ////////////
// Test Item: MISC_007, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
en_tm();
//		en_tm[]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x29, 0x01);  // Write reg 0x29 = 1
//		field[(shipmode_en,1)]
`NVT_STIM.en_vac1_cable_insert = 0;  // plugout vac1
//		plugout[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VAC1 set to 0V
//		vset[vac1,0,100e-6,0]
#100000000;  // delay 100e-3s
//		delay[100e-3]

`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_nqon = 1;
`NVT_STIM.vsrcNQON.ramp_vsrc_val(0, 100e-6);
#1000;
// pin NQON set to 0V
//		vset[nqon,0,100e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////