/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: AMUX_FULL ////////////
// Test Item: MISC_010, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.en_vac3_cable_insert = 1;  // plugin vac3
//		plugin[vac3]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VAC1 set to 4V
//		vset[vac1,4,100e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(8, 100e-6);
#1000;
// pin VAC2 set to 8V
//		vset[vac2,8,100e-6,0]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(12, 100e-6);
#1000;
// pin VAC3 set to 12V
//		vset[vac3,12,100e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x08);  // Write reg 0xC = 8
//		field[(VBUS_OVP,2)] // OVP=13V
I2CWriteSameData(DEV_ADDR, 0x08, 0x01);  // Write reg 0x8 = 1
//		field[(ac3_gate_on,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_pmid = 1;
`NVT_STIM.isrcPMID.ramp_isrc_val(1, 100e-6);
#1000;
// pin PMID current set to 1A
//		iset[pmid,1,100e-6,0]
`NVT_STIM.en_isrc_vacwl = 1;
`NVT_STIM.isrcVACWL.ramp_isrc_val(1, 100e-6);
#1000;
// pin VACWL current set to 1A
//		iset[vacwl,1,100e-6,0]

I2CWriteSameData(DEV_ADDR, 0x30, 0x10);  // Write reg 0x30 = 16
//		field[(IAC_SEL,4)] //KLV2-VAC2
I2CWriteSameData(DEV_ADDR, 0x11, 0x10);  // Write reg 0x11 = 16
//		field[(amux_en,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x11);  // Write reg 0x11 = 17
//		field[(channel_mux,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x12);  // Write reg 0x11 = 18
//		field[(channel_mux,2)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x13);  // Write reg 0x11 = 19
//		field[(channel_mux,3)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x14);  // Write reg 0x11 = 20
//		field[(channel_mux,4)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x15);  // Write reg 0x11 = 21
//		field[(channel_mux,5)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x16);  // Write reg 0x11 = 22
//		field[(channel_mux,6)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x17);  // Write reg 0x11 = 23
//		field[(channel_mux,7)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x18);  // Write reg 0x11 = 24
//		field[(channel_mux,8)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x19);  // Write reg 0x11 = 25
//		field[(channel_mux,9)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1A);  // Write reg 0x11 = 26
//		field[(channel_mux,10)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1B);  // Write reg 0x11 = 27
//		field[(channel_mux,11)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1C);  // Write reg 0x11 = 28
//		field[(channel_mux,12)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1D);  // Write reg 0x11 = 29
//		field[(channel_mux,13)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1E);  // Write reg 0x11 = 30
//		field[(channel_mux,14)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(channel_mux,15)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////