/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_VMCU_SWITCH ////////////
// Test Item: MISC_003, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(ac1_gate_on,1)]
`NVT_STIM.reg_en_mcu_load = 1;  // en_reg mcu_load, 1
//		en_reg[mcu_load,1]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x29, 0x60);  // Write reg 0x29 = 96
//		field[(VCC_FAVOR_VBAT,3),(VMCU_FAVOR_VBAT,0)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 10e-3);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x29, 0x70);  // Write reg 0x29 = 112
//		field[(VCC_FAVOR_VBAT,3),(VMCU_FAVOR_VBAT,1)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 10e-3);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,10e-3,0]

I2CWriteSameData(DEV_ADDR, 0x29, 0x40);  // Write reg 0x29 = 64
//		field[(VCC_FAVOR_VBAT,2),(VMCU_FAVOR_VBAT,0)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 10e-3);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x29, 0x50);  // Write reg 0x29 = 80
//		field[(VCC_FAVOR_VBAT,2),(VMCU_FAVOR_VBAT,1)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 10e-3);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,10e-3,0]
// Error: command format error: ====
//		====
I2CWriteSameData(DEV_ADDR, 0x29, 0x00);  // Write reg 0x29 = 0
//		field[(VCC_FAVOR_VBAT,0),(VMCU_FAVOR_VBAT,0)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 10e-3);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x29, 0x10);  // Write reg 0x29 = 16
//		field[(VCC_FAVOR_VBAT,0),(VMCU_FAVOR_VBAT,1)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VBAT set to 2V
//		vset[vbat,2,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.3, 10e-3);
#1000;
// pin VBAT set to 4.3V
//		vset[vbat,4.3,10e-3,0]

#4000000;  // delay 4e-3s
//		delay[4e-3]
`NVT_STIM.swVCC.set_ron_val(1);
`NVT_STIM.en_sw_vcc = 1;
#1000000;
// pin VCC resistor = 1¦¸
//		res[VCC,1]
#4000000;  // delay 4e-3s
//		delay[4e-3]
`NVT_STIM.swVCC.set_ron_val(1e6);
`NVT_STIM.en_sw_vcc = 1;
#1000000;
// pin VCC resistor = 1e6¦¸
//		res[VCC,1e6]
#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////