/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_wi_TX ////////////
// Test Item: MIX_702, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0C, 0x0C);  // Write reg 0xC = 12
I2CWriteSameData(DEV_ADDR, 0x0D, 0xE6);  // Write reg 0xD = 230
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(IBUS_SET,57),(VBUS_OVP,3),(VBUS_VOL_SET_L,230),(BUBO_MODE,1),(BUBO_EN,1)]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x04);  // Write reg 0xFF = 4
//		field[(MPP_EN,1)]
I2CWriteSameData(DEV_ADDR, 0x23, 0x01);  // Write reg 0x23 = 1
//		field[(drvh_en,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x23, 0x05);  // Write reg 0x23 = 5
I2CWriteSameData(DEV_ADDR, 0x31, 0x00);  // Write reg 0x31 = 0
//		field[(powerstage_en,1),(wl_drv_deadtime,0)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.reg_en_pwm = 1;
//		pwm_en[1]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 3906;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 50.0% duty, 0.0% shift
//		pwm_set[128e3,50,0,1]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x24, 0x90);  // Write reg 0x24 = 144
//		field[(tx_ocp,4),(tx_ocp_deg,2)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.swVRECT.set_ron_val(10);
`NVT_STIM.en_sw_vrect = 1;
#1000000;
// pin VRECT resistor = 10¦¸
//		res[vrect,10]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.swVRECT.set_ron_val(0.1);
`NVT_STIM.en_sw_vrect = 1;
#1000000;
// pin VRECT resistor = 0.1¦¸
//		res[vrect,0.1]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////