/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_SS_LARGE_LOAD_1 ////////////
// Test Item: MIX_701, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.swVAC2.set_ron_val(16);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 16¦¸
//		res[vac2,16]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x04);  // Write reg 0xFF = 4
//		field[(MPP_EN,1)]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x10);  // Write reg 0xC = 16
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1),(VBUS_OVP,4)]
I2CWriteSameData(DEV_ADDR, 0x0D, 0x44);  // Write reg 0xD = 68
//		field[(VBUS_VOL_SET_L,68)] //VBUS=16V
I2CWriteSameData(DEV_ADDR, 0x0C, 0x12);  // Write reg 0xC = 18
//		field[(VBUS_VOL_SET_L,68),(VBUS_VOL_SET_H,2)] //VBUS=16V
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
//		field[(IBUS_SET,57)] //IBUS 3A
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
//		field[(BUBO_MODE,1),(BUBO_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x30, 0x0C);  // Write reg 0x30 = 12
//		field[(IAC_SEL,3)] //KLV1-VAC1
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]

I2CWriteSameData(DEV_ADDR, 0x11, 0x10);  // Write reg 0x11 = 16
//		field[(amux_en,1)]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x15);  // Write reg 0x11 = 21
//		field[(channel_mux,5)] //IBUS 0.4
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x18);  // Write reg 0x11 = 24
//		field[(channel_mux,8)] //IAC
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x14);  // Write reg 0x11 = 20
//		field[(channel_mux,4)] //VBUS
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(channel_mux,15)] //V1P2
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////