/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_wi_AMUX ////////////
// Test Item: MIX_703, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
`NVT_STIM.en_vac3_cable_insert = 1;  // plugin vac3
//		plugin[vac3]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(9, 0.5e-6);
#1000;
// pin VAC3 set to 9V
//		vset[vac3,9,0.5e-6,0]
wait_warmup();
//		wait_warmup[]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x01);  // Write reg 0x8 = 1
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
I2CWriteSameData(DEV_ADDR, 0x0C, 0x04);  // Write reg 0xC = 4
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(VBUS_OVP,1),(AC3_GATE_ON,1),(IBUS_SET,57),(BUBO_EN,1),(amux_en,1),(CHANNEL_MUX,15)]

#3000000;  // delay 3e-3s
//		delay[3e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x15);  // Write reg 0x11 = 21
//		field[(CHANNEL_MUX,5)]
#250000;  // delay 0.25e-3s
//		delay[0.25e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(CHANNEL_MUX,15)]
#250000;  // delay 0.25e-3s
//		delay[0.25e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x10);  // Write reg 0x11 = 16
//		field[(CHANNEL_MUX,0)]
#250000;  // delay 0.25e-3s
//		delay[0.25e-3]
`NVT_STIM.en_vac3_cable_insert = 0;  // plugout vac3
//		plugout[vac3]
#10000000;  // delay 10e-3s
//		delay[10e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////