/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: RX_wi_BUCK_Normal_sequence4 ////////////
// Test Item: RX_603, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.9, 100e-6);
#1000;
// pin VBAT set to 3.9V
//		vset[vbat,3.9,100e-6,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(6, 100e-6);
#1000;
// pin VAC1 set to 6V
//		vset[vac1,6,100e-6,0]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x0C);  // Write reg 0xFF = 12
//		field[(rx_mode_en,1),(mpp_en,1)] // enable rx function
I2CWriteSameData(DEV_ADDR, 0x30, 0x20);  // Write reg 0x30 = 32
//		field[(RX_SW_PING_DET,1)] // enable rx ping det
I2CWriteSameData(DEV_ADDR, 0x33, 0x78);  // Write reg 0x33 = 120
//		field[(RX_SW_PING_DET_QUIT_EN,1)] // enable rx ping quit shipmode
I2CWriteSameData(DEV_ADDR, 0x32, 0x04);  // Write reg 0x32 = 4
//		field[(FSK_ALLOW,1)]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x0C);  // Write reg 0xC = 12
//		field[(VBUS_OVP,3)]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)] // wake up
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(ac1_gate_on,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x09, 0x06);  // Write reg 0x9 = 6
//		field[(IBUS_SET,17),(VBAT_CV,9),(BUBO_EN,1)] //IBUS=1A
wait(tb.IDUT.Idig.d2a_bubo_en);  // wait for tb.IDUT.Idig.d2a_bubo_en
//		wait[tb.IDUT.Idig.d2a_bubo_en]
`NVT_STIM.en_vsrc_vrect = 1;
`NVT_STIM.vsrcVRECT.ramp_vsrc_val(7, 100e-6);
#1000;
// pin VRECT set to 7V
//		vset[vrect,7,100e-6,0]
`NVT_STIM.reg_en_tx = 1;  // en_reg tx, 1
//		en_reg[tx,1]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 3906;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 50.0% duty, 0.0% shift
//		pwm_set[128e3,50,0,1]
#200;  // delay 0.2e-6s
//		delay[0.2e-6]

I2CWriteSameData(DEV_ADDR, 0x23, 0x02);  // Write reg 0x23 = 2
//		field[(POWERSTAGE_MODE,1)] // rx mode
I2CWriteSameData(DEV_ADDR, 0x23, 0x06);  // Write reg 0x23 = 6
//		field[(POWERSTAGE_EN,1)] // enable RX
wait(tb.IDUT.Idig.d2a_trx_en);  // wait for tb.IDUT.Idig.d2a_trx_en
//		wait[tb.IDUT.Idig.d2a_trx_en]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
//		field[(ac1_gate_on,0)]
`NVT_STIM.reg_en_drvh = 1;  // en_reg drvh, 1
//		en_reg[drvh,1]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.0, 100e-6);
#1000;
// pin VBAT set to 4.0V
//		vset[vbat,4.0,100e-6,0]
#400000;  // delay 0.4e-3s
//		delay[0.4e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.05, 100e-6);
#1000;
// pin VBAT set to 4.05V
//		vset[vbat,4.05,100e-6,0]
#400000;  // delay 0.4e-3s
//		delay[0.4e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.1, 100e-6);
#1000;
// pin VBAT set to 4.1V
//		vset[vbat,4.1,100e-6,0]
#400000;  // delay 0.4e-3s
//		delay[0.4e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.15, 100e-6);
#1000;
// pin VBAT set to 4.15V
//		vset[vbat,4.15,100e-6,0]
#400000;  // delay 0.4e-3s
//		delay[0.4e-3]
I2CWriteSameData(DEV_ADDR, 0x09, 0x02);  // Write reg 0x9 = 2
I2CWriteSameData(DEV_ADDR, 0x23, 0x02);  // Write reg 0x23 = 2
//		field[(BUBO_EN,0),(POWERSTAGE_EN,0)] //BUBO off
#400000;  // delay 0.4e-3s
//		delay[0.4e-3]
`NVT_STIM.reg_en_tx = 0;  // en_reg tx, 0
//		en_reg[tx,0]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 3906;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 0;
#1000;
// PWM: 128000.0Hz, 50.0% duty, 0.0% shift
//		pwm_set[128e3,50,0,0]
#400000;  // delay 0.4e-3s
//		delay[0.4e-3]

#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////