/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: EFUSE BURN ////////////
// Test Item: TM003, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]

I2CWriteSameData(DEV_ADDR, 0xF0, 0x05);  // Write reg 0xF0 = 5
I2CWriteSameData(DEV_ADDR, 0xFC, 0x08);  // Write reg 0xFC = 8
//		field[(d2a_trim_bg,5),(d2a_trim_qdt_vth_cmp,1)]
I2CWriteSameData(DEV_ADDR, 0x53, 0x19);  // Write reg 0x53 = 25
//		field[(NVM_PROG_ALL,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x53, 0x18);  // Write reg 0x53 = 24
//		field[(NVM_PROG_ALL,0)]

I2CWriteSameData(DEV_ADDR, 0xF0, 0x01);  // Renew reg 0xF0 = 1
I2CWriteSameData(DEV_ADDR, 0xFC, 0x38);  // Renew reg 0xFC = 56
//		field_renew[(d2a_trim_bg,1),(d2a_trim_qdt_vth_cmp,7)]
I2CWriteSameData(DEV_ADDR, 0x53, 0x1A);  // Write reg 0x53 = 26
//		field[(NVM_RELOAD,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0xF0, 0x02);  // Renew reg 0xF0 = 2
I2CWriteSameData(DEV_ADDR, 0xFC, 0x18);  // Renew reg 0xFC = 24
//		field_renew[(d2a_trim_bg,2),(d2a_trim_qdt_vth_cmp,3)]
I2CWriteSameData(DEV_ADDR, 0x53, 0xD8);  // Write reg 0x53 = 216
//		field[(NVM_REG_SET,3)]
I2CWriteSameData(DEV_ADDR, 0x53, 0xDA);  // Write reg 0x53 = 218
//		field[(NVM_RELOAD,1),(NVM_REG_SET,3)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////