/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: SCAN&IDDQ ////////////
// Test Item: TM002, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
en_scan();
//		en_scan[]
#10000000;  // delay 10e-3s
//		delay[10e-3]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(4, 1e-6);
#1000;
// pin VDM set to 4V
//		vset[vdm,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(0, 1e-6);
#1000;
// pin VDM set to 0V
//		vset[vdm,0,1e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////