/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: Iq_Shipmode ////////////
// Test Item: TM001_2, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x29, 0x01);  // Write reg 0x29 = 1
//		field[(SHIPMODE_EN,1)]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VAC1 set to 0V
//		vset[vac1,0,100e-6,0]
#60000000;  // delay 60e-3s
//		delay[60e-3]

// Error: �����ʽ����: // Check IQ from VBAT
//		// Check IQ from VBAT
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////