/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC1_PRST_DMO_A ////////////
// Test Item: TM108_1, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3, 100e-6);
#1000;
// pin VBAT set to 3V
//		vset[vbat,3,100e-6,0]
wait_warmup();
//		wait_warmup[]

key1_open();
//		key1_open[]
I2CWriteSameData(DEV_ADDR, 0x56, 0x16);  // Write reg 0x56 = 22
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,22)]
I2CWriteSameData(DEV_ADDR, 0x71, 0x3B);  // Write reg 0x71 = 59
//		field[(D2A_DMO_CHANNEL_SEL,1),(D2A_DMA_CHANNEL_SEL,1),(DM_CHANNEL_SEL_OVER_WRITE,1),(D2A_DMA_EN,1),(D2A_DMO_EN,1)]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(10, 1e-3);
#1000;
// pin VAC1 set to 10V
//		vset[vac1,10,1e-3,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(0, 1e-3);
#1000;
// pin VAC1 set to 0V
//		vset[vac1,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////