/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: QDT_LG1_LG2_CHECK_COMP ////////////
// Test Item: TM1003, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x01);  // Write reg 0x57 = 1
I2CWriteSameData(DEV_ADDR, 0x5A, 0x10);  // Write reg 0x5A = 16
I2CWriteSameData(DEV_ADDR, 0x5B, 0x80);  // Write reg 0x5B = 128
//		field[(en_i2c_ctrl,1),(d2a_qdt_en_comp,1),(d2a_qdt_en,1)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////