/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: LP_HR_0P5U ////////////
// Test Item: TM103, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x04);  // Write reg 0x5E = 4
//		field[(EN_ATEST0,1),(ATEST0_MUX,4)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1, 100e-6);
#1000;
// pin VDM set to 1V
//		vset[vdm,1,100e-6,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////