/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_HT_VBAT ////////////
// Test Item: TM107, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x56, 0x29);  // Write reg 0x56 = 41
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,41)]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(2, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 2V
//		vset[vbus,2,100e-6,1]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,1e-3,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(2, 1e-3);
#1000;
// pin VBUS set to 2V
//		vset[vbus,2,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////