/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: LP_VBG ////////////
// Test Item: TM101, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.2, 100e-6);
#1000;
// pin VDM set to 1.2V
//		vset[vdm,1.2,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x01);  // Write reg 0x5E = 1
//		field[(EN_ATEST0,1),(ATEST0_MUX,1)]
`NVT_STIM.en_vsrc_vdm = 0;  // disable vdm
//		vset_off[vdm]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////