/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: QDT_VTH_COMP ////////////
// Test Item: TM1004, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x01);  // Write reg 0x57 = 1
I2CWriteSameData(DEV_ADDR, 0x5A, 0x10);  // Write reg 0x5A = 16
I2CWriteSameData(DEV_ADDR, 0x5B, 0x80);  // Write reg 0x5B = 128
//		field[(en_i2c_ctrl,1),(d2a_qdt_en_comp,1),(d2a_qdt_en,1)]
I2CWriteSameData(DEV_ADDR, 0x27, 0x30);  // Write reg 0x27 = 48
//		field[(Q_PRE_CHG_VOL,3)]
I2CWriteSameData(DEV_ADDR, 0x28, 0x0C);  // Write reg 0x28 = 12
//		field[(Q_DET_RATIO,3)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x46);  // Write reg 0x56 = 70
I2CWriteSameData(DEV_ADDR, 0x57, 0x09);  // Write reg 0x57 = 9
//		field[(DMUX_EN,1),(DMUX_SEL,70)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 100e-6);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,100e-6,0]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x0B);  // Write reg 0x57 = 11
I2CWriteSameData(DEV_ADDR, 0x5E, 0x22);  // Write reg 0x5E = 34
//		field[(EN_ATEST0,1),(ATEST0_MUX,34)]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 100e-6);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,100e-6,0]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,100e-6,0]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////