/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: QDT VPCHG SHORT CURRENT ////////////
// Test Item: TM1009, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x01);  // Write reg 0x57 = 1
I2CWriteSameData(DEV_ADDR, 0x5A, 0x40);  // Write reg 0x5A = 64
I2CWriteSameData(DEV_ADDR, 0x5B, 0x80);  // Write reg 0x5B = 128
//		field[(en_i2c_ctrl,1),(d2a_qdt_en_prechg,1),(d2a_qdt_en,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(1.2, 100e-6);
#1000;
// pin SW1 set to 1.2V
//		vset[sw1,1.2,100e-6,0]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(0, 100e-6);
#1000;
// pin SW1 set to 0V
//		vset[sw1,0,100e-6,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////