/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC2_PRST ////////////
// Test Item: TM109, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3, 100e-6);
#1000;
// pin VBAT set to 3V
//		vset[vbat,3,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x56, 0x15);  // Write reg 0x56 = 21
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,21)]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(10, 1e-3);
#1000;
// pin VAC2 set to 10V
//		vset[vac2,10,1e-3,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(0, 1e-3);
#1000;
// pin VAC2 set to 0V
//		vset[vac2,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////