/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_CUR_LIMIT_VBAT_PATH ////////////
// Test Item: TM117, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

`NVT_STIM.vsrcVCC.ramp_vsrc_val(1, 1e-3);
`NVT_STIM.en_vsrc_vcc = 1;
#1000;
// pin VCC set to 1V
//		vset[vcc,1,1e-3,1]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////