/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_FLT1_AGC_AUTO_GAIN ////////////
// Test Item: TM1107, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x10);  // Write reg 0xFF = 16
//		field[(DEMO_UPDATE,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x06);  // Write reg 0x57 = 6
I2CWriteSameData(DEV_ADDR, 0x5D, 0x22);  // Write reg 0x5D = 34
//		field[(EN_ATEST0,1),(EN_ATEST1,1),(D2A_ADM_ATEST0_MUX,2),(D2A_ADM_ATEST1_MUX,2)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x34);  // Write reg 0x25 = 52
//		field[(SEL_DMA,2)]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(0.5, 10e-6);
#1000;
// pin VCN set to 0.5V
//		vset[vcn,0.5,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]

#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x36, 0x02);  // Write reg 0x36 = 2
//		field[(DMA_SEL_AGC_GAIN,1)]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x36, 0x04);  // Write reg 0x36 = 4
//		field[(DMA_SEL_AGC_GAIN,2)]
#250000;  // delay 250e-6s
//		delay[250e-6]

#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x36, 0x00);  // Write reg 0x36 = 0
//		field[(DMA_SEL_AGC_GAIN,0)]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.497, 10e-6);
#1000;
// pin VCP set to 0.497V
//		vset[vcp,0.497,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.503, 10e-6);
#1000;
// pin VCP set to 0.503V
//		vset[vcp,0.503,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x36, 0x06);  // Write reg 0x36 = 6
//		field[(DMA_SEL_AGC_GAIN,3)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////