/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBAT_HT_3P1V ////////////
// Test Item: TM112, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2.5, 1e-3);
#1000;
// pin VBAT set to 2.5V
//		vset[vbat,2.5,1e-3,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,1e-3,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x56, 0x28);  // Write reg 0x56 = 40
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
I2CWriteSameData(DEV_ADDR, 0x58, 0x20);  // Write reg 0x58 = 32
//		field[(DMUX_EN,1),(DMUX_SEL,40),(D2A_REGN_TM_EN,1)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 10e-3);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,10e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////