/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_FLT2_AGC_FIXED_GAIN ////////////
// Test Item: TM1116, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x06);  // Write reg 0x57 = 6
I2CWriteSameData(DEV_ADDR, 0x5D, 0x55);  // Write reg 0x5D = 85
//		field[(EN_ATEST0,1),(EN_ATEST1,1),(D2A_ADM_ATEST0_MUX,5),(D2A_ADM_ATEST1_MUX,5)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x3F);  // Write reg 0x25 = 63
//		field[(SEL_DMO,3)]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(0.5, 10e-6);
#1000;
// pin VCN set to 0.5V
//		vset[vcn,0.5,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x34, 0x02);  // Write reg 0x34 = 2
//		field[(DMO_SEL_AGC_GAIN,1)]

#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]

`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
I2CWriteSameData(DEV_ADDR, 0x34, 0x0A);  // Write reg 0x34 = 10
//		field[(DMO_FIXED_AGC_GAIN,1)]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////