/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_VPEAK_TRACK ////////////
// Test Item: TM1102, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(0.5, 100e-6);
#1000;
// pin VCN set to 0.5V
//		vset[vcn,0.5,100e-6,0]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 100e-6);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x3F);  // Write reg 0x25 = 63
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
I2CWriteSameData(DEV_ADDR, 0x5D, 0x70);  // Write reg 0x5D = 112
//		field[(VCAP_RATIO,0),(SEL_DMO,3),(D2A_ADM_ATEST1_MUX,7),(EN_ATEST1,1)]
I2CWriteSameData(DEV_ADDR, 0x71, 0x34);  // Write reg 0x71 = 52
//		field[(D2A_DMA_EN,1),(D2A_DMA_MODE,1),(DM_CHANNEL_SEL_OVER_WRITE,1)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCN set to 1V
//		vset[vcn,1,10e-6,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-9);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-9,0]
#1400;  // delay 1.4e-6s
//		delay[1.4e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(2, 10e-9);
#1000;
// pin VCP set to 2V
//		vset[vcp,2,10e-9,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////