/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC_WL_PRST ////////////
// Test Item: TM110_2, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x40);  // Write reg 0x56 = 64
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,64)]
`NVT_STIM.en_vsrc_vac_wl = 1;
`NVT_STIM.vsrcVAC_WL.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VAC_WL set to 5V
//		vset[vac_wl,5,1e-3,0]
`NVT_STIM.en_vsrc_vac_wl = 1;
`NVT_STIM.vsrcVAC_WL.ramp_vsrc_val(0, 1e-3);
#1000;
// pin VAC_WL set to 0V
//		vset[vac_wl,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////