/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_VAC_PATH_ACC ////////////
// Test Item: TM115, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2.5, 100e-6);
#1000;
// pin VBAT set to 2.5V
//		vset[vbat,2.5,100e-6,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]

`NVT_STIM.en_isrc_vcc = 1;
`NVT_STIM.isrcVCC.ramp_isrc_val(0.03, 1e-3);
#1000;
// pin VCC current set to 0.03A
//		iset[vcc,0.03,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////