/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_UV ////////////
// Test Item: TM113, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3, 1e-3);
#1000;
// pin VBAT set to 3V
//		vset[vbat,3,1e-3,0]

`NVT_STIM.en_vsrc_vcc = 1;
`NVT_STIM.vsrcVCC.ramp_vsrc_val(2.5, 1e-3);
#1000;
// pin VCC set to 2.5V
//		vset[vcc,2.5,1e-3,0]
`NVT_STIM.en_vsrc_vcc = 1;
`NVT_STIM.vsrcVCC.ramp_vsrc_val(0, 1e-3);
#1000;
// pin VCC set to 0V
//		vset[vcc,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////