/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_FLT2_ZERO_CMP ////////////
// Test Item: TM1119, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5.5, 100e-6);
#1000;
// pin VBAT set to 5.5V
//		vset[vbat,5.5,100e-6,0]
`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(0.3, 100e-6);
#1000;
// pin AMUX set to 0.3V
//		vset[amux,0.3,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x06);  // Write reg 0x57 = 6
I2CWriteSameData(DEV_ADDR, 0x5D, 0x55);  // Write reg 0x5D = 85
//		field[(EN_ATEST0,1),(EN_ATEST1,1),(D2A_ADM_ATEST0_MUX,5),(D2A_ADM_ATEST1_MUX,5)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x3F);  // Write reg 0x25 = 63
//		field[(SEL_DMO,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x42);  // Write reg 0x56 = 66
I2CWriteSameData(DEV_ADDR, 0x57, 0x0E);  // Write reg 0x57 = 14
//		field[(DMUX_EN,1),(DMUX_SEL,66)]
I2CWriteSameData(DEV_ADDR, 0x34, 0x02);  // Write reg 0x34 = 2
//		field[(DMO_SEL_AGC_GAIN,1)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VDM set to 2V
//		vset[vdm,2,10e-3,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VDM set to 0V
//		vset[vdm,0,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x35, 0x01);  // Write reg 0x35 = 1
//		field[(DMO_SEL_CMP_HYS,1)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VDM set to 2V
//		vset[vdm,2,10e-3,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VDM set to 0V
//		vset[vdm,0,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x35, 0x02);  // Write reg 0x35 = 2
//		field[(DMO_SEL_CMP_HYS,2)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VDM set to 2V
//		vset[vdm,2,10e-3,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VDM set to 0V
//		vset[vdm,0,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x35, 0x03);  // Write reg 0x35 = 3
//		field[(DMO_SEL_CMP_HYS,3)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2, 10e-3);
#1000;
// pin VDM set to 2V
//		vset[vdm,2,10e-3,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VDM set to 0V
//		vset[vdm,0,10e-3,0]

#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////