/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_PHASE_DET_T2V ////////////
// Test Item: TM1104, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x10);  // Write reg 0xFF = 16
//		field[(DEMO_UPDATE,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x2C);  // Write reg 0x25 = 44
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5D, 0x07);  // Write reg 0x5D = 7
//		field[(SEL_DMA,1),(EN_ATEST0,1),(D2A_ADM_ATEST0_MUX,7)]
I2CWriteSameData(DEV_ADDR, 0x5C, 0x40);  // Write reg 0x5C = 64
//		field[(D2A_ADM_TM_T2V,1)]

//		field[(D2A_VCAP_PHASE_ICHG_OPT,0)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Renew reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,48),(ovrd_value,3)]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]

`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]

`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 10e-9);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 10e-9);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,10e-9,0]
#2000;  // delay 2e-6s
//		delay[2e-6]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////