/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_VDM_CHANNEL_FUNCTION_TEST ////////////
// Test Item: TM1121, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_vac_wl = 1;
`NVT_STIM.vsrcVAC_WL.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC_WL set to 5V
//		vset[vac_wl,5,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x3D);  // Write reg 0x25 = 61
//		field[(SEL_DMO,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x39);  // Write reg 0x25 = 57
I2CWriteSameData(DEV_ADDR, 0x71, 0x08);  // Write reg 0x71 = 8
//		field[(D2A_DMO_EN,1),(SEL_DMO_CMP_OUT,0)]
I2CWriteSameData(DEV_ADDR, 0x71, 0x28);  // Write reg 0x71 = 40
//		field[(DM_CHANNEL_SEL_OVER_WRITE,1)]
I2CWriteSameData(DEV_ADDR, 0x23, 0x04);  // Write reg 0x23 = 4
//		field[(POWERSTAGE_EN,1)]
I2CWriteSameData(DEV_ADDR, 0x6F, 0x64);  // Write reg 0x6F = 100
//		field[(DIS_TX_BST_UV_GD_PROTECT,1)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
I2CWriteSameData(DEV_ADDR, 0x25, 0x3D);  // Write reg 0x25 = 61
//		field[(SEL_DMO_CMP_OUT,1)]

`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2.1, 1e-6);
#1000;
// pin VDM set to 2.1V
//		vset[vdm,2.1,1e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.9, 1e-6);
#1000;
// pin VDM set to 1.9V
//		vset[vdm,1.9,1e-6,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////