/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_VCAP_SNS_GAIN_ACC ////////////
// Test Item: TM1101, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VCN set to 0V
//		vset[vcn,0,100e-6,0]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0.1, 100e-6);
#1000;
// pin VCP set to 0.1V
//		vset[vcp,0.1,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x71, 0x34);  // Write reg 0x71 = 52
//		field[(D2A_DMA_EN,1),(D2A_DMA_MODE,1),(DM_CHANNEL_SEL_OVER_WRITE,1)]
I2CWriteSameData(DEV_ADDR, 0x26, 0x01);  // Write reg 0x26 = 1
//		field[(VCAP_RATIO,1)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 1000e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,1000e-6,0]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 1000e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,1000e-6,0]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(1, 1000e-6);
#1000;
// pin VCN set to 1V
//		vset[vcn,1,1000e-6,0]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(0, 1000e-6);
#1000;
// pin VCN set to 0V
//		vset[vcn,0,1000e-6,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////