/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_VREF_1P2 ////////////
// Test Item: TM1123, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
I2CWriteSameData(DEV_ADDR, 0x5D, 0x60);  // Write reg 0x5D = 96
//		field[(EN_ATEST1,1),(D2A_ADM_ATEST1_MUX,6),(D2A_ADM_ATEST1_MUX_H,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////