/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DEMO_FLT1_CHANNEL_FUNCTION_TEST ////////////
// Test Item: TM1122, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_vac_wl = 1;
`NVT_STIM.vsrcVAC_WL.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC_WL set to 5V
//		vset[vac_wl,5,100e-6,0]
`NVT_STIM.en_vsrc_vcn = 1;
`NVT_STIM.vsrcVCN.ramp_vsrc_val(0.5, 100e-6);
#1000;
// pin VCN set to 0.5V
//		vset[vcn,0.5,100e-6,0]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 100e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x10);  // Write reg 0xFF = 16
//		field[(DEMO_UPDATE,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x25, 0x34);  // Write reg 0x25 = 52
//		field[(SEL_DMA,2)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2C);  // Write reg 0x67 = 44
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,44),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x14);  // Write reg 0x25 = 20
I2CWriteSameData(DEV_ADDR, 0x71, 0x10);  // Write reg 0x71 = 16
//		field[(D2A_DMA_EN,1),(SEL_DMA_CMP_OUT,0)]
I2CWriteSameData(DEV_ADDR, 0x71, 0x30);  // Write reg 0x71 = 48
//		field[(DM_CHANNEL_SEL_OVER_WRITE,1)]
I2CWriteSameData(DEV_ADDR, 0x23, 0x04);  // Write reg 0x23 = 4
//		field[(POWERSTAGE_EN,1)]
I2CWriteSameData(DEV_ADDR, 0x6F, 0x64);  // Write reg 0x6F = 100
//		field[(DIS_TX_BST_UV_GD_PROTECT,1)]

#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
I2CWriteSameData(DEV_ADDR, 0x25, 0x34);  // Write reg 0x25 = 52
//		field[(SEL_DMA_CMP_OUT,1)]

`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(0, 10e-6);
#1000;
// pin VCP set to 0V
//		vset[vcp,0,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
`NVT_STIM.en_vsrc_vcp = 1;
`NVT_STIM.vsrcVCP.ramp_vsrc_val(1, 10e-6);
#1000;
// pin VCP set to 1V
//		vset[vcp,1,10e-6,0]
#250000;  // delay 250e-6s
//		delay[250e-6]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////