/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_VBAT_PATH_ACC ////////////
// Test Item: TM116, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 1e-3);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,1e-3,0]

wait_warmup();
//		wait_warmup[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_vcc = 1;
`NVT_STIM.isrcVCC.ramp_isrc_val(0.05, 1e-3);
#1000;
// pin VCC current set to 0.05A
//		iset[vcc,0.05,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////