/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_VBUS_PATH_ACC ////////////
// Test Item: TM114, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5.2, 100e-6);
#1000;
// pin VAC1 set to 5.2V
//		vset[vac1,5.2,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1),(REGN_VOL_SET,0)]
`NVT_STIM.en_isrc_vcc = 1;
`NVT_STIM.isrcVCC.ramp_isrc_val(0.05, 1e-3);
#1000;
// pin VCC current set to 0.05A
//		iset[vcc,0.05,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////