/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_DRVH ////////////
// Test Item: TM1209, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2F);  // Renew reg 0x67 = 47
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,47),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2D);  // Renew reg 0x67 = 45
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,45),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Renew reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,48),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x0C);  // Write reg 0xFF = 12
//		field[(mpp_en,1),(rx_mode_en,1)]
`NVT_STIM.en_vsrc_bst2_sw2 = 1;
`NVT_STIM.vsrcBST2_SW2.ramp_vsrc_val(4, 100e-6);
#1000;
// pin BST2_SW2 set to 4V
//		vset[bst2_sw2,4,100e-6,0]
`NVT_STIM.en_vsrc_sw2 = 1;
`NVT_STIM.vsrcSW2.ramp_vsrc_val(1, 100e-6);
#1000;
// pin SW2 set to 1V
//		vset[sw2,1,100e-6,0]

I2CWriteSameData(DEV_ADDR, 0x23, 0x01);  // Write reg 0x23 = 1
//		field[(DRVH_EN,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
// Error: �����ʽ����: //TEST DRVH pin to BST2 or SW2 resistor.
//		//TEST DRVH pin to BST2 or SW2 resistor.

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////