/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_RX_VTH_SW1 ////////////
// Test Item: TM1210, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x0C);  // Write reg 0xFF = 12
//		field[(mpp_en,1),(rx_mode_en,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2E);  // Renew reg 0x67 = 46
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,46),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2F);  // Renew reg 0x67 = 47
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,47),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2D);  // Renew reg 0x67 = 45
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,45),(ovrd_value,3)]
`NVT_STIM.en_vsrc_sw2 = 1;
`NVT_STIM.vsrcSW2.ramp_vsrc_val(2, 100e-6);
#1000;
// pin SW2 set to 2V
//		vset[sw2,2,100e-6,0]
`NVT_STIM.en_vsrc_sw2 = 1;
`NVT_STIM.vsrcSW2.ramp_vsrc_val(0, 100e-6);
#1000;
// pin SW2 set to 0V
//		vset[sw2,0,100e-6,0]

// Error: �����ʽ����: // Check LG1 toggle. Catch SW2 voltage when LG1 toggle.
//		// Check LG1 toggle. Catch SW2 voltage when LG1 toggle.
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(2, 100e-6);
#1000;
// pin SW1 set to 2V
//		vset[sw1,2,100e-6,0]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(0, 100e-6);
#1000;
// pin SW1 set to 0V
//		vset[sw1,0,100e-6,0]
// Error: �����ʽ����: // Check LG2 toggle. Catch SW1 voltage when LG2 toggle.
//		// Check LG2 toggle. Catch SW1 voltage when LG2 toggle.
#2000000;  // delay 2e-3s
//		delay[2e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////