/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_SW1_DET_VTH ////////////
// Test Item: TM1207, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x56, 0x3B);  // Renew reg 0x56 = 59
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Renew reg 0x57 = 8
//		field_renew[(DMUX_EN,1),(DMUX_SEL,59)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(4, 1e-3);
#1000;
// pin SW1 set to 4V
//		vset[sw1,4,1e-3,0]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(0, 1e-3);
#1000;
// pin SW1 set to 0V
//		vset[sw1,0,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]

I2CWriteSameData(DEV_ADDR, 0x56, 0x3C);  // Renew reg 0x56 = 60
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Renew reg 0x57 = 8
//		field_renew[(DMUX_EN,1),(DMUX_SEL,60)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_sw2 = 1;
`NVT_STIM.vsrcSW2.ramp_vsrc_val(4, 1e-3);
#1000;
// pin SW2 set to 4V
//		vset[sw2,4,1e-3,0]
`NVT_STIM.en_vsrc_sw2 = 1;
`NVT_STIM.vsrcSW2.ramp_vsrc_val(0, 1e-3);
#1000;
// pin SW2 set to 0V
//		vset[sw2,0,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////