/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_SW2_LS_OCP ////////////
// Test Item: TM1204, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]

//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2F);  // Renew reg 0x67 = 47
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,47),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2D);  // Renew reg 0x67 = 45
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,45),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Renew reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,48),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x5C, 0x04);  // Renew reg 0x5C = 4
//		field_renew[(D2A_TRX_TM_SW2_OCP_DEG_BYPASS,1)]
I2CWriteSameData(DEV_ADDR, 0x24, 0x60);  // Renew reg 0x24 = 96
//		field_renew[(TX_OCP,3)]

I2CWriteSameData(DEV_ADDR, 0x56, 0x38);  // Renew reg 0x56 = 56
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Renew reg 0x57 = 8
//		field_renew[(DMUX_EN,1),(DMUX_SEL,56)]
`NVT_STIM.swSW2_PGNDWL.set_ron_val(100e-3);
`NVT_STIM.en_sw_sw2_pgndwl = 1;
#1000000;
// pin SW2_PGNDWL resistor = 100e-3��
//		res[sw2_pgndwl,100e-3]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM2 set to 4V
//		vset[pwm2,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm2 = 1;
`NVT_STIM.vsrcPWM2.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM2 set to 0V
//		vset[pwm2,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_isrc_vccext_sw2 = 1;
`NVT_STIM.isrcVCCEXT_SW2.ramp_isrc_val(2, 1e-3);
#1000;
// pin VCCEXT_SW2 current set to 2A
//		iset[vccext_sw2, 2,1e-3,0]
`NVT_STIM.en_isrc_vccext_sw2 = 1;
`NVT_STIM.isrcVCCEXT_SW2.ramp_isrc_val(0, 1e-3);
#1000;
// pin VCCEXT_SW2 current set to 0A
//		iset[vccext_sw2,0,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x24, 0xC0);  // Renew reg 0x24 = 192
//		field_renew[(TX_OCP,6)]
`NVT_STIM.en_isrc_vccext_sw2 = 1;
`NVT_STIM.isrcVCCEXT_SW2.ramp_isrc_val(2, 1e-3);
#1000;
// pin VCCEXT_SW2 current set to 2A
//		iset[vccext_sw2, 2,1e-3,0]
`NVT_STIM.en_isrc_vccext_sw2 = 1;
`NVT_STIM.isrcVCCEXT_SW2.ramp_isrc_val(0, 1e-3);
#1000;
// pin VCCEXT_SW2 current set to 0A
//		iset[vccext_sw2,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////