/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_LG1_HG1_Ron_Roff ////////////
// Test Item: TM1200, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]

//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2F);  // Renew reg 0x67 = 47
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,47),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2D);  // Renew reg 0x67 = 45
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,45),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Renew reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,48),(ovrd_value,3)]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(0.1, 100e-6);
#1000;
// pin SW1 set to 0.1V
//		vset[sw1,0.1,100e-6,0]
`NVT_STIM.en_vsrc_bst1_sw1 = 1;
`NVT_STIM.vsrcBST1_SW1.ramp_vsrc_val(4, 100e-6);
#1000;
// pin BST1_SW1 set to 4V
//		vset[bst1_sw1,4,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]

`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]

`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#10000;  // delay 10e-6s
//		delay[10e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////