/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VMCU_VCC_PATH_ACC ////////////
// Test Item: TM124, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]

entertestmode();
//		en_tm[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_vmcu = 1;
`NVT_STIM.isrcVMCU.ramp_isrc_val(0.05, 1e-3);
#1000;
// pin VMCU current set to 0.05A
//		iset[vmcu,0.05,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////