/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_BST_UV_GD ////////////
// Test Item: TM1205, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]

//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2F);  // Renew reg 0x67 = 47
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,47),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2D);  // Renew reg 0x67 = 45
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,45),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Renew reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,48),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x5C, 0x02);  // Renew reg 0x5C = 2
//		field_renew[(D2A_TRX_TM_BOOTGD_DEG_BYPASS,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]

I2CWriteSameData(DEV_ADDR, 0x56, 0x39);  // Renew reg 0x56 = 57
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Renew reg 0x57 = 8
//		field_renew[(DMUX_EN,1),(DMUX_SEL,57)]
`NVT_STIM.en_vsrc_bst1_sw1 = 1;
`NVT_STIM.vsrcBST1_SW1.ramp_vsrc_val(4, 1000e-6);
#1000;
// pin BST1_SW1 set to 4V
//		vset[bst1_sw1,4,1000e-6,0]
`NVT_STIM.en_vsrc_bst1_sw1 = 1;
`NVT_STIM.vsrcBST1_SW1.ramp_vsrc_val(0, 1000e-6);
#1000;
// pin BST1_SW1 set to 0V
//		vset[bst1_sw1,0,1000e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x56, 0x3A);  // Renew reg 0x56 = 58
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Renew reg 0x57 = 8
//		field_renew[(DMUX_EN,1),(DMUX_SEL,58)]
`NVT_STIM.en_vsrc_bst2_sw2 = 1;
`NVT_STIM.vsrcBST2_SW2.ramp_vsrc_val(4, 1000e-6);
#1000;
// pin BST2_SW2 set to 4V
//		vset[bst2_sw2,4,1000e-6,0]
`NVT_STIM.en_vsrc_bst2_sw2 = 1;
`NVT_STIM.vsrcBST2_SW2.ramp_vsrc_val(0, 1000e-6);
#1000;
// pin BST2_SW2 set to 0V
//		vset[bst2_sw2,0,1000e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////