/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VMCU_CUR_LIMIT_VBAT_PATH ////////////
// Test Item: TM125, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x29, 0x10);  // Write reg 0x29 = 16
//		field[(WAKE_UP,1),(VMCU_FAVOR_VBAT,1)]
`NVT_STIM.en_vsrc_vmcu = 1;
`NVT_STIM.vsrcVMCU.ramp_vsrc_val(0.5, 1e-3);
#1000;
// pin VMCU set to 0.5V
//		vset[vmcu,0.5,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////