/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRX_BST1_RON ////////////
// Test Item: TM1206, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
`NVT_STIM.en_isrc_bst1 = 1;
`NVT_STIM.isrcBST1.ramp_isrc_val(0.1e-3, 100e-6);
#1000;
// pin BST1 current set to 0.1e-3A
//		iset[bst1,0.1e-3,100e-6,0]
`NVT_STIM.en_vsrc_sw1 = 1;
`NVT_STIM.vsrcSW1.ramp_vsrc_val(3, 100e-6);
#1000;
// pin SW1 set to 3V
//		vset[sw1,3,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2F);  // Renew reg 0x67 = 47
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,47),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x2D);  // Renew reg 0x67 = 45
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,45),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Renew reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Renew reg 0x68 = 48
//		field_renew[(D2A_OVRD_SEL,48),(ovrd_value,3)]
I2CWriteSameData(DEV_ADDR, 0x5C, 0x10);  // Renew reg 0x5C = 16
//		field_renew[(D2A_TRX_TM_EN_BST_EXT_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]

`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]

`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-6);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-6,0]
#5000;  // delay 5e-6s
//		delay[5e-6]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-6);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////