/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_VBAT_HT_2P8 ////////////
// Test Item: TM129, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,1e-3,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x29, 0x10);  // Write reg 0x29 = 16
//		field[(WAKE_UP,1),(VMCU_FAVOR_VBAT,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x3E);  // Write reg 0x56 = 62
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,62)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3, 1e-3);
#1000;
// pin VBAT set to 3V
//		vset[vbat,3,1e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 1e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////