/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBAT_PATH_ON_VCC ////////////
// Test Item: TM128, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.4, 100e-6);
#1000;
// pin VBAT set to 3.4V
//		vset[vbat,3.4,100e-6,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x29, 0x20);  // Write reg 0x29 = 32
//		field[(WAKE_UP,1),(VCC_FAVOR_VBAT,1)]
#3000000;  // delay 3e-3s
//		delay[3e-3]
I2CWriteSameData(DEV_ADDR, 0x56, 0x28);  // Write reg 0x56 = 40
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,40)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 10e-3);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,10e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////