/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VCC_VBAT_HT_3P7 ////////////
// Test Item: TM130, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,1e-3,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x29, 0x20);  // Write reg 0x29 = 32
//		field[(WAKE_UP,1),(VCC_FAVOR_VBAT,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x3F);  // Write reg 0x56 = 63
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,63)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.5, 10e-3);
#1000;
// pin VBAT set to 4.5V
//		vset[vbat,4.5,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x29, 0x40);  // Write reg 0x29 = 64
//		field[(WAKE_UP,1),(VCC_FAVOR_VBAT,2)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.5, 10e-3);
#1000;
// pin VBAT set to 4.5V
//		vset[vbat,4.5,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,10e-3,0]
I2CWriteSameData(DEV_ADDR, 0x29, 0x60);  // Write reg 0x29 = 96
//		field[(WAKE_UP,1),(VCC_FAVOR_VBAT,3)]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.5, 10e-3);
#1000;
// pin VBAT set to 4.5V
//		vset[vbat,4.5,10e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,10e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////