/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TDIE_WARM_TM ////////////
// Test Item: TM138, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBAT set to 5V
//		vset[vbat,5,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x11);  // Write reg 0x56 = 17
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,17)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x58, 0x40);  // Write reg 0x58 = 64
//		field[(D2A_BG_TM_TSD,1)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////