/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IZTC_1UA ////////////
// Test Item: TM133, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBAT set to 5V
//		vset[vbat,5,100e-6,0]
`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(1, 100e-6);
#1000;
// pin AMUX set to 1V
//		vset[amux,1,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x08);  // Write reg 0x5E = 8
//		field[(EN_ATEST0,1),(ATEST0_MUX,8)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1, 100e-6);
#1000;
// pin VDM set to 1V
//		vset[vdm,1,100e-6,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////