/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IPD_VAC3 ////////////
// Test Item: TM207, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x08, 0x10);  // Write reg 0x8 = 16
//		field[(VAC3_PULLDOWN,1)]

`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(1, 1e-3);
#1000;
// pin VAC3 set to 1V
//		vset[vac3,1,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(4, 1e-3);
#1000;
// pin VAC3 set to 4V
//		vset[vac3,4,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////