/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: R_INT ////////////
// Test Item: TM202, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x67, 0x31);  // Write reg 0x67 = 49
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,49),(OVRD_VALUE,3)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////