/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VTH_SDA_IN ////////////
// Test Item: TM201, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBAT set to 5V
//		vset[vbat,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x56, 0x06);  // Write reg 0x56 = 6
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,6)]

`NVT_STIM.en_vsrc_sda = 1;
`NVT_STIM.vsrcSDA.ramp_vsrc_val(3, 1e-3);
#1000;
// pin SDA set to 3V
//		vset[sda,3,1e-3,0]
`NVT_STIM.en_vsrc_sda = 1;
`NVT_STIM.vsrcSDA.ramp_vsrc_val(0, 1e-3);
#1000;
// pin SDA set to 0V
//		vset[sda,0,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////