/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IPD_VBUS ////////////
// Test Item: TM204, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,1]

wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x08, 0x08);  // Write reg 0x8 = 8
//		field[(VBUS_PULLDOWN,1)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
//		field[(VBUS_PULLDOWN,0)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x08);  // Write reg 0x8 = 8
//		field[(VBUS_PULLDOWN,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////