/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: PWM1_Vth ////////////
// Test Item: TM214, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x2E);  // Write reg 0x56 = 46
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,46)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x30);  // Write reg 0x67 = 48
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,48),(ovrd_value,3)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(4, 1e-3);
#1000;
// pin PWM1 set to 4V
//		vset[pwm1,4,1e-3,0]
`NVT_STIM.en_vsrc_pwm1 = 1;
`NVT_STIM.vsrcPWM1.ramp_vsrc_val(0, 1e-3);
#1000;
// pin PWM1 set to 0V
//		vset[pwm1,0,1e-3,0]

#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////