/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC2_SNK_DET_VTH_RELMODE ////////////
// Test Item: TM211, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x07, 0x05);  // Write reg 0x7 = 5
//		field[(VAC2_APORT_DET_ENABLE,1),(VAC_SNK_DET_SEL,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x2C);  // Write reg 0x56 = 44
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,44)]
#10000000;  // delay 10e-3s
//		delay[10e-3]

`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(3, 2e-3);
#1000;
// pin VAC2 set to 3V
//		vset[vac2,3,2e-3,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(0, 2e-3);
#1000;
// pin VAC2 set to 0V
//		vset[vac2,0,2e-3,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(3, 0.1e-3);
#1000;
// pin VAC2 set to 3V
//		vset[vac2,3,0.1e-3,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(0, 0.1e-3);
#1000;
// pin VAC2 set to 0V
//		vset[vac2,0,0.1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////