/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: DMA pulldown resistor ////////////
// Test Item: TM222, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
entertestmode();
//		en_tm[]

I2CWriteSameData(DEV_ADDR, 0x71, 0x31);  // Write reg 0x71 = 49
//		field[(DM_CHANNEL_SEL_OVER_WRITE,1),(D2A_DMA_EN,1),(D2A_DMA_CHANNEL_SEL,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x16);  // Write reg 0x56 = 22
//		field[(DMUX_SEL,22)]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 10e-3);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,10e-3,0]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(0, 10e-3);
#1000;
// pin VAC1 set to 0V
//		vset[vac1,0,10e-3,0]

#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////