/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_OVP_VTH3 ////////////
// Test Item: TM402, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x14);  // Write reg 0xC = 20
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x20);  // Write reg 0x56 = 32
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
I2CWriteSameData(DEV_ADDR, 0xFF, 0x04);  // Write reg 0xFF = 4
//		field[(WAKE_UP,1),(VBUS_OVP,5),(DMUX_EN,1),(MPP_EN,1),(DMUX_SEL,32)]

`NVT_STIM.vsrcVBUS.ramp_vsrc_val(4, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 4V
//		vset[vbus,4,100e-6,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(20, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 20V
//		vset[vbus,20,1e-3,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(4, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 4V
//		vset[vbus,4,1e-3,1]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////