/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBAT_OVP ////////////
// Test Item: TM408, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x1C);  // Write reg 0x56 = 28
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(WAKE_UP,1),(DMUX_EN,1),(DMUX_SEL,28),(VBAT_CV,9)]

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VBAT set to 5V
//		vset[vbat,5,1e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(0, 1e-3);
#1000;
// pin VBAT set to 0V
//		vset[vbat,0,1e-3,0]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////