/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_HT_4P8V ////////////
// Test Item: TM409, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x1F);  // Write reg 0x56 = 31
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(WAKE_UP,1),(DMUX_EN,1),(DMUX_SEL,31),(BUBO_MODE,1)]

`NVT_STIM.vsrcVBUS.ramp_vsrc_val(4, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 4V
//		vset[vbus,4,100e-6,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(7, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 7V
//		vset[vbus,7,1e-3,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(4, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 4V
//		vset[vbus,4,1e-3,1]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////