/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_REVI_VTH ////////////
// Test Item: TM403, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x1E);  // Write reg 0x56 = 30
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(WAKE_UP,1),(DMUX_EN,1),(DMUX_SEL,30)]

`NVT_STIM.vsrcVBUS.ramp_vsrc_val(3.7, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 3.7V
//		vset[vbus,3.7,100e-6,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(4.5, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 4.5V
//		vset[vbus,4.5,1e-3,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(3.7, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 3.7V
//		vset[vbus,3.7,1e-3,1]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////