/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC1_FB ////////////
// Test Item: TM418, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x11);  // Write reg 0x11 = 17
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,1),(EN_ATEST0,1),(ATEST0_MUX,31)]

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,1e-3,0]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////