/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC2_FB ////////////
// Test Item: TM419, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x12);  // Write reg 0x11 = 18
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,2),(EN_ATEST0,1),(ATEST0_MUX,31)]

`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(10, 1e-3);
#1000;
// pin VAC2 set to 10V
//		vset[vac2,10,1e-3,0]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////