/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_FB ////////////
// Test Item: TM421, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x14);  // Write reg 0x11 = 20
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,4),(EN_ATEST0,1),(ATEST0_MUX,31)]

`NVT_STIM.vsrcVBUS.ramp_vsrc_val(4, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 4V
//		vset[vbus,4,1e-3,1]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(10, 1e-3);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 10V
//		vset[vbus,10,1e-3,1]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////