/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VREF_TRIM ////////////
// Test Item: TM424, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x13);  // Write reg 0x5E = 19
//		field[(WAKE_UP,1),(EN_ATEST0,1),(ATEST0_MUX,19)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////