/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VREF_1P2V_BUF ////////////
// Test Item: TM425, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
I2CWriteSameData(DEV_ADDR, 0x58, 0x02);  // Write reg 0x58 = 2
//		field[(WAKE_UP,1),(EN_ATEST1,1),(ATEST1_MUX,2),(DIS_NTC_DETECTION_ANALOG,1)]

#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////