/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IR_CABLE_COMP1 ////////////
// Test Item: TM432, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x0F, 0x01);  // Write reg 0xF = 1
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x19);  // Write reg 0x56 = 25
I2CWriteSameData(DEV_ADDR, 0x57, 0x0E);  // Write reg 0x57 = 14
I2CWriteSameData(DEV_ADDR, 0x58, 0x11);  // Write reg 0x58 = 17
I2CWriteSameData(DEV_ADDR, 0x5E, 0x16);  // Write reg 0x5E = 22
//		field[(WAKE_UP,1),(BUBO_MODE,1),(IR_COMP_TYPE,0)(IR_COMP,1),(VCLAMP,0),(D2A_MNT_TM_EN,1),(EN_ATEST0,1),(ATEST0_MUX,22),(EN_ATEST1,1),(ATEST1_MUX,1),(DIS_NTC_DETECTION_ANALOG,1),(DMUX_EN,1),(DMUX_SEL,25)]

`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(2.4, 1e-3);
#1000;
// pin AMUX set to 2.4V
//		vset[amux,2.4,1e-3,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(1.2, 1e-3);
#1000;
// pin AMUX set to 1.2V
//		vset[amux,1.2,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////