/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: CV_BUF_TRIM ////////////
// Test Item: TM439_1, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,100e-6,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.15, 1e-3);
#1000;
// pin VBAT set to 4.15V
//		vset[vbat,4.15,1e-3,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x7F);  // Write reg 0xE = 127
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
I2CWriteSameData(DEV_ADDR, 0x61, 0x53);  // Write reg 0x61 = 83
//		field[(VBAT_CV,9),(IBAT_LIMIT,7),(IBUS_SET,127),(VBUS_LOOP_DISABLE,1),(EN_ATEST1,1),(D2A_BUBO_ATEST1,5),(DIS_NTC_DETECTION_ANALOG,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x59, 0x21);  // Write reg 0x59 = 33
//		field[(D2A_BUBO_TM_DIS_CLK,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x09);  // Write reg 0x67 = 9
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,9)(ovrd_value,3)]
#1000000;  // delay 1e-3s
//		delay[1e-3]


            `NVT_STIM.reg_en_SVLP_BU = 1;
            `NVT_STIM.reg_en_SVLP_VBATLP = 1;
//		ServeLoopCTRL[1]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vbat = 0;  // disable vbat
//		vset_off[vbat]
I2CWriteSameData(DEV_ADDR, 0xF8, 0x01);  // Write reg 0xF8 = 1
//		field[(d2a_trim_mnt_cv_buf_h,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF8, 0x02);  // Write reg 0xF8 = 2
//		field[(d2a_trim_mnt_cv_buf_h,2)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF8, 0x04);  // Write reg 0xF8 = 4
//		field[(d2a_trim_mnt_cv_buf_h,4)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF8, 0x08);  // Write reg 0xF8 = 8
//		field[(d2a_trim_mnt_cv_buf_h,8)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////