/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_VBUS_EA_TRIM ////////////
// Test Item: TM441, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(12, 1e-3);
#1000;
// pin VBUS set to 12V
//		vset[vbus,12,1e-3,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x0C, 0x01);  // Write reg 0xC = 1
I2CWriteSameData(DEV_ADDR, 0x0D, 0x7C);  // Write reg 0xD = 124
I2CWriteSameData(DEV_ADDR, 0x0E, 0x7F);  // Write reg 0xE = 127
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
//		field[(WAKE_UP,1),(BUBO_MODE,1),(VBUS_VOL_SET_L,124),(VBUS_VOL_SET_H,1),(IBAT_LIMIT,7),(IBUS_SET,127),(EN_ATEST1,1),(D2A_BUBO_ATEST1,5),(DIS_NTC_DETECTION_ANALOG,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x05);  // Write reg 0x57 = 5
I2CWriteSameData(DEV_ADDR, 0x59, 0x80);  // Write reg 0x59 = 128
//		field[(EN_I2C_CTRL,1),(D2A_BUBO_TM_DIS_VBATLOOP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x59, 0xA1);  // Write reg 0x59 = 161
//		field[(D2A_BUBO_TM_DIS_CLK,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]


            `NVT_STIM.reg_en_SVLP_BO = 1;
            `NVT_STIM.reg_en_SVLP_VBUSLP = 1;
//		ServeLoopCTRL[3]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vbus = 0;  // disable vbus
//		vset_off[vbus]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x04);  // Write reg 0xF6 = 4
//		field[(d2a_trim_mnt_vbus_ea_os_bo,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x08);  // Write reg 0xF6 = 8
//		field[(d2a_trim_mnt_vbus_ea_os_bo,2)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x10);  // Write reg 0xF6 = 16
//		field[(d2a_trim_mnt_vbus_ea_os_bo,4)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x20);  // Write reg 0xF6 = 32
//		field[(d2a_trim_mnt_vbus_ea_os_bo,8)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x40);  // Write reg 0xF6 = 64
//		field[(d2a_trim_mnt_vbus_ea_os_bo,16)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x80);  // Write reg 0xF6 = 128
//		field[(d2a_trim_mnt_vbus_ea_os_bo,32)]
#4000000;  // delay 4e-3s
//		delay[4e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////