/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_VBUS_EA_TRIM ////////////
// Test Item: TM442, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5.5, 1e-3);
#1000;
// pin VBUS set to 5.5V
//		vset[vbus,5.5,1e-3,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x7F);  // Write reg 0xE = 127
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
//		field[(WAKE_UP,1),(BUBO_MODE,0),(VBUS_VOL_SET_L,10),(IBAT_LIMIT,7),(IBUS_SET,127),(EN_ATEST1,1),(D2A_BUBO_ATEST1,5),(DIS_NTC_DETECTION_ANALOG,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x05);  // Write reg 0x57 = 5
I2CWriteSameData(DEV_ADDR, 0x59, 0x80);  // Write reg 0x59 = 128
//		field[(EN_I2C_CTRL,1),(D2A_BUBO_TM_DIS_VBATLOOP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x59, 0xA1);  // Write reg 0x59 = 161
//		field[(D2A_BUBO_TM_DIS_CLK,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]


            `NVT_STIM.reg_en_SVLP_BU = 1;
            `NVT_STIM.reg_en_SVLP_VBUSLP = 1;
//		ServeLoopCTRL[2]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vbus = 0;  // disable vbus
//		vset_off[vbus]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF5, 0x10);  // Write reg 0xF5 = 16
//		field[(d2a_trim_mnt_vbus_ea_os_bu_l,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF5, 0x20);  // Write reg 0xF5 = 32
//		field[(d2a_trim_mnt_vbus_ea_os_bu_l,2)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF5, 0x40);  // Write reg 0xF5 = 64
//		field[(d2a_trim_mnt_vbus_ea_os_bu_l,4)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF5, 0x80);  // Write reg 0xF5 = 128
//		field[(d2a_trim_mnt_vbus_ea_os_bu_l,8)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x01);  // Write reg 0xF6 = 1
//		field[(d2a_trim_mnt_vbus_ea_os_bu_h,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF6, 0x02);  // Write reg 0xF6 = 2
//		field[(d2a_trim_mnt_vbus_ea_os_bu_h,2)]
#4000000;  // delay 4e-3s
//		delay[4e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////