/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_BUF_TRIM ////////////
// Test Item: TM440, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
wait_warmup();
//		wait_warmup[]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0C, 0x01);  // Write reg 0xC = 1
I2CWriteSameData(DEV_ADDR, 0x0D, 0x7C);  // Write reg 0xD = 124
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x05);  // Write reg 0x57 = 5
I2CWriteSameData(DEV_ADDR, 0x58, 0x04);  // Write reg 0x58 = 4
//		field[(en_i2c_ctrl,1)(WAKE_UP,1),(BUBO_MODE,1),(BUBO_EN,1),(VBUS_VOL_SET_L,124),(VBUS_VOL_SET_H,1),(EN_ATEST1,1),(ATEST1_MUX,4),(DIS_NTC_DETECTION_ANALOG,1)]

#4000000;  // delay 4e-3s
//		delay[4e-3]
I2CWriteSameData(DEV_ADDR, 0xF7, 0x01);  // Write reg 0xF7 = 1
//		field[(d2a_trim_mnt_vbus_buf,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF7, 0x02);  // Write reg 0xF7 = 2
//		field[(d2a_trim_mnt_vbus_buf,2)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF7, 0x04);  // Write reg 0xF7 = 4
//		field[(d2a_trim_mnt_vbus_buf,4)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF7, 0x08);  // Write reg 0xF7 = 8
//		field[(d2a_trim_mnt_vbus_buf,8)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF7, 0x10);  // Write reg 0xF7 = 16
//		field[(d2a_trim_mnt_vbus_buf,16)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xF7, 0x20);  // Write reg 0xF7 = 32
//		field[(d2a_trim_mnt_vbus_buf,32)]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////