/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: AC_DRIVER_SS_Vth ////////////
// Test Item: TM504, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
I2CWriteSameData(DEV_ADDR, 0x60, 0x20);  // Write reg 0x60 = 32
//		field[(AC1_GATE_SS_EN,1),(AC1_GATE_ON,1)]

`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(6, 1e-3);
#1000;
// pin VBUS set to 6V
//		vset[vbus,6,1e-3,0]
#100000000;  // delay 100e-3s
//		delay[100e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////