/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: ACDRV fastoff off trig ////////////
// Test Item: TM503_1, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x0F);  // Write reg 0x5E = 15
//		field[(AC1_GATE_ON,1),(EN_ATEST0,1),(ATEST0_MUX,15)]
#10000000;  // delay 10e-3s
//		delay[10e-3]

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(10, 20e-6);
#1000;
// pin VAC1 set to 10V
//		vset[vac1,10,20e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_acdrv1 = 1;
`NVT_STIM.vsrcACDRV1.ramp_vsrc_val(10, 2e-3);
#1000;
// pin ACDRV1 set to 10V
//		vset[acdrv1,10,2e-3,0]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
//		field[(AC1_GATE_ON,0)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_acdrv1 = 1;
`NVT_STIM.vsrcACDRV1.ramp_vsrc_val(5, 2e-3);
#1000;
// pin ACDRV1 set to 5V
//		vset[acdrv1,5,2e-3,0]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////