/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: ACDRV_BIAS_1UA ////////////
// Test Item: TM506, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1, 100e-6);
#1000;
// pin VDM set to 1V
//		vset[vdm,1,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x01);  // Write reg 0x57 = 1
//		field[(en_i2c_ctrl,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
I2CWriteSameData(DEV_ADDR, 0x57, 0x03);  // Write reg 0x57 = 3
I2CWriteSameData(DEV_ADDR, 0x5E, 0x0D);  // Write reg 0x5E = 13
//		field[(AC1_GATE_ON,1),(EN_ATEST0,1),(ATEST0_MUX,13)]

#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////