/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: AC_DRIVER_ON_VOL ////////////
// Test Item: TM500, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(AC1_GATE_ON,1)]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 20e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,20e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x06);  // Write reg 0x8 = 6
//		field[(AC2_GATE_ON,1)]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 20e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,20e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x07);  // Write reg 0x8 = 7
//		field[(AC3_GATE_ON,1)]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(5, 20e-6);
#1000;
// pin VAC3 set to 5V
//		vset[vac3,5,20e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////