/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: ACDRV_VDD_IQ ////////////
// Test Item: TM507, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x01);  // Write reg 0x57 = 1
//		field[(en_i2c_ctrl,1)]

I2CWriteSameData(DEV_ADDR, 0x60, 0x04);  // Write reg 0x60 = 4
//		field[(D2A_AC1_GATE_FORCE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x60, 0x06);  // Write reg 0x60 = 6
//		field[(D2A_AC2_GATE_FORCE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x60, 0x07);  // Write reg 0x60 = 7
//		field[(D2A_AC3_GATE_FORCE_ON,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////