/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: AC_DRIVER_ON_CLP ////////////
// Test Item: TM501, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x07);  // Write reg 0x8 = 7
//		field[(AC1_GATE_ON,1),(AC2_GATE_ON,1),(AC3_GATE_ON,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]

`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(12, 20e-6);
#1000;
// pin VAC1 set to 12V
//		vset[vac1,12,20e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(12, 20e-6);
#1000;
// pin VAC2 set to 12V
//		vset[vac2,12,20e-6,0]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(12, 20e-6);
#1000;
// pin VAC3 set to 12V
//		vset[vac3,12,20e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x03);  // Write reg 0x8 = 3
//		field[(AC1_GATE_ON,0)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x01);  // Write reg 0x8 = 1
//		field[(AC2_GATE_ON,0)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
//		field[(AC3_GATE_ON,0)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////