/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: ACDRV_CLAMP_CMP ////////////
// Test Item: TM511, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
I2CWriteSameData(DEV_ADDR, 0x56, 0x21);  // Write reg 0x56 = 33
I2CWriteSameData(DEV_ADDR, 0x57, 0x0A);  // Write reg 0x57 = 10
I2CWriteSameData(DEV_ADDR, 0x5E, 0x0E);  // Write reg 0x5E = 14
//		field[(AC1_GATE_ON,1),(EN_ATEST0,1),(ATEST0_MUX,14),(DMUX_EN,1),(DMUX_SEL,33)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(10, 10e-3);
#1000;
// pin VAC1 set to 10V
//		vset[vac1,10,10e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////