/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BUCK_RCS_TRIM ////////////
// Test Item: TM604, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x01);  // Write reg 0x57 = 1
//		field[(WAKE_UP,1),(EN_I2C_CTRL,1)]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x59);  // Write reg 0xE = 89
I2CWriteSameData(DEV_ADDR, 0x59, 0x31);  // Write reg 0x59 = 49
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1),(D2A_BUBO_TM_DIS_CLK,1),(IBUS_SET,89),(VBUS_LOOP_DISABLE,1),(BUBO_MODE,0),(D2A_BUBO_TM_ISCALE_DOWN,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x25);  // Write reg 0x56 = 37
I2CWriteSameData(DEV_ADDR, 0x57, 0x09);  // Write reg 0x57 = 9
I2CWriteSameData(DEV_ADDR, 0x5F, 0x05);  // Write reg 0x5F = 5
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,5)]
#50000000;  // delay 50e-3s
//		delay[50e-3]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x02);  // Write reg 0x5A = 2
//		field[(D2A_BUBO_TM_HSON,1)]

#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(4, 10e-3);
#1000;
// pin SW current set to 4A
//		iset[sw,4,10e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////