/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VC_HIGH_CLAMP[2]&ISCALE_RATIO ////////////
// Test Item: TM603, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(2, 1e-3);
#1000;
// pin VDM set to 2V
//		vset[vdm,2,1e-3,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x0E, 0x59);  // Write reg 0xE = 89
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x59, 0x01);  // Write reg 0x59 = 1
I2CWriteSameData(DEV_ADDR, 0x5B, 0x01);  // Write reg 0x5B = 1
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
I2CWriteSameData(DEV_ADDR, 0x70, 0x02);  // Write reg 0X70 = 2
//		field[(D2A_BUBO_EN_FORCE_ON,1),(IBUS_SET,89),(VBUS_LOOP_DISABLE,1),(BUBO_MODE,1),(EN_ATEST0,1),(D2A_BUBO_ATEST0_MUX,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1),(DIS_NTC_DETECTION_ANALOG,1),(BUBO_EA_CLAMP_H_VTH,1),(BUBO_SHORT_RCOMP,1)]
I2CWriteSameData(DEV_ADDR, 0x03, 0x60);  // Write reg 0x3 = 96
I2CWriteSameData(DEV_ADDR, 0x59, 0x21);  // Write reg 0x59 = 33
//		field[(D2A_BUBO_TM_DIS_CLK,1),(FSM_STAT,6)]
#50000000;  // delay 50e-3s
//		delay[50e-3]
I2CWriteSameData(DEV_ADDR, 0x59, 0x31);  // Write reg 0x59 = 49
//		field[(D2A_BUBO_TM_ISCALE_DOWN,1)]

#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////