/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOT_VOLTAGE_DROP ////////////
// Test Item: TM606, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x01);  // Write reg 0x5A = 1
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1),(D2A_BUBO_TM_LSON,1),(BUBO_MODE,0)]
#5000;  // delay 5e-6s
//		delay[5e-6]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x00);  // Write reg 0x5A = 0
//		field[(D2A_BUBO_TM_LSON,0)]
#5000;  // delay 5e-6s
//		delay[5e-6]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x01);  // Write reg 0x5A = 1
//		field[(D2A_BUBO_TM_LSON,1)]
#5000;  // delay 5e-6s
//		delay[5e-6]

`NVT_STIM.en_isrc_bst = 1;
`NVT_STIM.isrcBST.ramp_isrc_val(0.1, 1e-5);
#1000;
// pin BST current set to 0.1A
//		iset[bst,0.1,1e-5,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////