/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST_RCS_TRIM ////////////
// Test Item: TM605, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x0E, 0x59);  // Write reg 0xE = 89
I2CWriteSameData(DEV_ADDR, 0x59, 0x11);  // Write reg 0x59 = 17
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
I2CWriteSameData(DEV_ADDR, 0x70, 0x02);  // Write reg 0X70 = 2
//		field[(D2A_BUBO_EN_FORCE_ON,1),(IBUS_SET,89),(VBUS_LOOP_DISABLE,1),(BUBO_MODE,1),(D2A_BUBO_TM_ISCALE_DOWN,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1),(BUBO_SHORT_RCOMP,1)]
#10000;  // delay 1e-5s
//		delay[1e-5]
I2CWriteSameData(DEV_ADDR, 0x59, 0x31);  // Write reg 0x59 = 49
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x56, 0x25);  // Write reg 0x56 = 37
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
I2CWriteSameData(DEV_ADDR, 0x5F, 0x06);  // Write reg 0x5F = 6
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,6)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x01);  // Write reg 0x5A = 1
//		field[(D2A_BUBO_TM_LSON,1)]

#5000000;  // delay 5e-3s
//		delay[5e-3]
`NVT_STIM.en_isrc_pmid_sw = 1;
`NVT_STIM.isrcPMID_SW.ramp_isrc_val(4, 1e-3);
#1000;
// pin PMID_SW current set to 4A
//		iset[pmid_sw,4,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////