/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: PSM_THREHOLD ////////////
// Test Item: TM615, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x59, 0x20);  // Write reg 0x59 = 32
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1),(D2A_BUBO_TM_DIS_CLK,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
I2CWriteSameData(DEV_ADDR, 0x5B, 0x50);  // Write reg 0x5B = 80
I2CWriteSameData(DEV_ADDR, 0x70, 0x02);  // Write reg 0X70 = 2
//		field[(EN_ATEST1,1),(D2A_BUBO_ATEST1_MUX,5),(DIS_NTC_DETECTION_ANALOG,1),(BUBO_SHORT_RCOMP,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x25);  // Write reg 0x56 = 37
I2CWriteSameData(DEV_ADDR, 0x57, 0x0C);  // Write reg 0x57 = 12
I2CWriteSameData(DEV_ADDR, 0x5F, 0x03);  // Write reg 0x5F = 3
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,3)]

`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(1.3, 1e-3);
#1000;
// pin AMUX set to 1.3V
//		vset[amux,1.3,1e-3,0]
`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(1.5, 1e-3);
#1000;
// pin AMUX set to 1.5V
//		vset[amux,1.5,1e-3,0]
`NVT_STIM.en_vsrc_amux = 1;
`NVT_STIM.vsrcAMUX.ramp_vsrc_val(1.3, 1e-3);
#1000;
// pin AMUX set to 1.3V
//		vset[amux,1.3,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////