/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRICKLE_CURRENT1 ////////////
// Test Item: TM627, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(2.5, 100e-6);
#1000;
// pin VBAT set to 2.5V
//		vset[vbat,2.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x02);  // Write reg 0x5A = 2
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_TM_HSON,1),(D2A_BUBO_EN_FORCE_ON,1),(BUBO_MODE,0),(ITRIKLE,0)]
#500000;  // delay 5e-4s
//		delay[5e-4]
I2CWriteSameData(DEV_ADDR, 0x59, 0x20);  // Write reg 0x59 = 32
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#50000;  // delay 5e-5s
//		delay[5e-5]
I2CWriteSameData(DEV_ADDR, 0x56, 0x25);  // Write reg 0x56 = 37
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
I2CWriteSameData(DEV_ADDR, 0x5F, 0x05);  // Write reg 0x5F = 5
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,5)]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(1.5, 2e-3);
#1000;
// pin SW current set to 1.5A
//		iset[sw,1.5,2e-3,0]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(-1, 1e-3);
#1000;
// pin SW current set to -1A
//		iset[sw,-1,1e-3,0]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(1.5, 2e-3);
#1000;
// pin SW current set to 1.5A
//		iset[sw,1.5,2e-3,0]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(-1, 1e-3);
#1000;
// pin SW current set to -1A
//		iset[sw,-1,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x10);  // Write reg 0xB = 16
//		field[(ITRIKLE,1)]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(1.5, 2e-3);
#1000;
// pin SW current set to 1.5A
//		iset[sw,1.5,2e-3,0]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(-1, 1e-3);
#1000;
// pin SW current set to -1A
//		iset[sw,-1,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x20);  // Write reg 0xB = 32
//		field[(ITRIKLE,2)]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(1.5, 2e-3);
#1000;
// pin SW current set to 1.5A
//		iset[sw,1.5,2e-3,0]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(-1, 1e-3);
#1000;
// pin SW current set to -1A
//		iset[sw,-1,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x30);  // Write reg 0xB = 48
//		field[(ITRIKLE,3)]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(1.5, 2e-3);
#1000;
// pin SW current set to 1.5A
//		iset[sw,1.5,2e-3,0]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(-1, 1e-3);
#1000;
// pin SW current set to -1A
//		iset[sw,-1,1e-3,0]
`NVT_STIM.en_isrc_pmid_sw = 1;
`NVT_STIM.isrcPMID_SW.ramp_isrc_val(1, 1e-3);
#1000;
// pin PMID_SW current set to 1A
//		iset[pmid_sw,1,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x01);  // Write reg 0x5A = 1
//		field[(D2A_BUBO_TM_HSON,0),(D2A_BUBO_TM_LSON,1)]
I2CWriteSameData(DEV_ADDR, 0x5F, 0x06);  // Write reg 0x5F = 6
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,6)]
`NVT_STIM.en_isrc_pmid_sw = 1;
`NVT_STIM.isrcPMID_SW.ramp_isrc_val(-1, 2e-3);
#1000;
// pin PMID_SW current set to -1A
//		iset[pmid_sw,-1,2e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////