/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TRICKLE_PERIOD ////////////
// Test Item: TM628, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.1, 100e-6);
#1000;
// pin VBAT set to 4.1V
//		vset[vbat,4.1,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x02);  // Write reg 0x5A = 2
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_TM_HSON,1),(D2A_BUBO_EN_FORCE_ON,1),(BUBO_MODE,0),(ITRIKLE,0),(ITRIKLE_HALF,0)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x03);  // Write reg 0x67 = 3
//		field[(D2A_OVRD_SEL,3)]
#50000;  // delay 5e-5s
//		delay[5e-5]
I2CWriteSameData(DEV_ADDR, 0x68, 0x20);  // Write reg 0x68 = 32
//		field[(OVRD_VALUE,2)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x25);  // Write reg 0x56 = 37
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
I2CWriteSameData(DEV_ADDR, 0x5F, 0x09);  // Write reg 0x5F = 9
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,9)]
#100000;  // delay 1e-4s
//		delay[1e-4]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x10);  // Write reg 0xB = 16
//		field[(ITRIKLE,1),(ITRIKLE_HALF,0)]
#100000;  // delay 1e-4s
//		delay[1e-4]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x40);  // Write reg 0xB = 64
//		field[(ITRIKLE,0),(ITRIKLE_HALF,1)]
#100000;  // delay 1e-4s
//		delay[1e-4]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x50);  // Write reg 0xB = 80
//		field[(ITRIKLE,1),(ITRIKLE_HALF,1)]
#100000;  // delay 1e-4s
//		delay[1e-4]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x70);  // Write reg 0xB = 112
//		field[(ITRIKLE,3),(ITRIKLE_HALF,1)]
#100000;  // delay 1e-4s
//		delay[1e-4]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x80);  // Write reg 0xB = 128
//		field[(ITRIKLE,4),(ITRIKLE_HALF,1)]
#100000;  // delay 1e-4s
//		delay[1e-4]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////