/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBAT_LOOP_GM_TRIM ////////////
// Test Item: TM635, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x7F);  // Write reg 0xE = 127
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x06);  // Write reg 0x57 = 6
I2CWriteSameData(DEV_ADDR, 0x5E, 0x12);  // Write reg 0x5E = 18
I2CWriteSameData(DEV_ADDR, 0x61, 0x53);  // Write reg 0x61 = 83
//		field[(WAKE_UP,1),(VBAT_CV,9),(IBAT_LIMIT,7),(IBUS_SET,127),(VBUS_LOOP_DISABLE,1),(EN_ATEST1,1),(D2A_BUBO_ATEST1,5),(EN_ATEST0,1),(ATEST0_MUX,18),(DIS_NTC_DETECTION_ANALOG,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x59, 0x21);  // Write reg 0x59 = 33
//		field[(D2A_BUBO_TM_DIS_CLK,1),(D2A_BUBO_TM_DIS_COMPH_SLP,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x09);  // Write reg 0x67 = 9
I2CWriteSameData(DEV_ADDR, 0x68, 0x30);  // Write reg 0x68 = 48
//		field[(D2A_OVRD_SEL,9)(ovrd_value,3)]
#1000000;  // delay 1e-3s
//		delay[1e-3]


            `NVT_STIM.reg_en_SVLP_BU = 1;
            `NVT_STIM.reg_en_SVLP_VBATLP = 1;
//		ServeLoopCTRL[1]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vbat = 0;  // disable vbat
//		vset_off[vbat]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_comp = 1;
`NVT_STIM.isrcCOMP.ramp_isrc_val(10e-6, 100e-6);
#1000;
// pin COMP current set to 10e-6A
//		iset[COMP,10e-6,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xFB, 0x80);  // Write reg 0xFB = 128
//		field[(d2a_trim_bubo_iptat_l,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xFC, 0x01);  // Write reg 0xFC = 1
//		field[(d2a_trim_bubo_iptat_h,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xFC, 0x02);  // Write reg 0xFC = 2
//		field[(d2a_trim_bubo_iptat_h,2)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0xFC, 0x04);  // Write reg 0xFC = 4
//		field[(d2a_trim_bubo_iptat_h,4)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////