/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_LOOP_TEST_IN_BOOST ////////////
// Test Item: TM634_3, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x0E, 0x25);  // Write reg 0xE = 37
I2CWriteSameData(DEV_ADDR, 0x61, 0x53);  // Write reg 0x61 = 83
//		field[(BUBO_MODE,1),(IBUS_SET,37),(VBUS_LOOP_DISABLE,1)]

//		field[(DIS_NTC_DETECTION_ANALOG,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x19);  // Write reg 0x5E = 25
//		field[(EN_ATEST0,1),(ATEST0_MUX,25)]
I2CWriteSameData(DEV_ADDR, 0x59, 0x84);  // Write reg 0x59 = 132
I2CWriteSameData(DEV_ADDR, 0x70, 0x02);  // Write reg 0X70 = 2
//		field[(D2A_BUBO_TM_DIS_BST_UVLO_LOCAL,1),(BUBO_SHORT_RCOMP,1),(D2A_BUBO_TM_DIS_VBATLOOP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x03);  // Write reg 0x57 = 3
//		field[(EN_I2C_CTRL,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x59, 0xA4);  // Write reg 0x59 = 164
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]

`NVT_STIM.en_isrc_vbus = 1;
`NVT_STIM.isrcVBUS.ramp_isrc_val(2, 1e-3);
#1000;
// pin VBUS current set to 2A
//		iset[vbus,2,1e-3,0]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0xF4, 0x08);  // Write reg 0xF4 = 8
//		field[(D2A_TRIM_IBUS_LOOP_OS,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0xF4, 0x10);  // Write reg 0xF4 = 16
//		field[(D2A_TRIM_IBUS_LOOP_OS,2)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0xF4, 0x20);  // Write reg 0xF4 = 32
//		field[(D2A_TRIM_IBUS_LOOP_OS,4)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0xF4, 0x40);  // Write reg 0xF4 = 64
//		field[(D2A_TRIM_IBUS_LOOP_OS,8)]
#5000000;  // delay 5e-3s
//		delay[5e-3]
$finish;
//		finish[0]

/////////////////////// End of Auto-generated Code ////////////