/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_LOOP_GM_BUCK ////////////
// Test Item: TM638, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]
`NVT_STIM.en_isrc_vbus = 1;
`NVT_STIM.isrcVBUS.ramp_isrc_val(-0.5, 100e-6);
#1000;
// pin VBUS current set to -0.5A
//		iset[vbus,-0.5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x00);  // Write reg 0xE = 0
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x18);  // Write reg 0x5E = 24
I2CWriteSameData(DEV_ADDR, 0x61, 0x53);  // Write reg 0x61 = 83
//		field[(BUBO_MODE,0),(IBUS_SET,0),(VBUS_LOOP_DISABLE,1),(EN_ATEST0,1),(ATEST0_MUX,24),(DIS_NTC_DETECTION_ANALOG,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x03);  // Write reg 0x57 = 3
I2CWriteSameData(DEV_ADDR, 0x70, 0x02);  // Write reg 0X70 = 2
//		field[(EN_I2C_CTRL,1),(VBUS_LOOP_Disable,1),(BUBO_SHORT_RCOMP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x59, 0x20);  // Write reg 0x59 = 32
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_comp = 1;
`NVT_STIM.vsrcCOMP.ramp_vsrc_val(2, 1e-3);
#1000;
// pin COMP set to 2V
//		vset[comp,2,1e-3,0]
#20000000;  // delay 20e-3s
//		delay[20e-3]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x01);  // Write reg 0xE = 1
//		field[(IBUS_SET,1)]
#20000000;  // delay 20e-3s
//		delay[20e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////