/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBUS_LOOP_INDICTOR_BU ////////////
// Test Item: TM646, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(9, 100e-6);
#1000;
// pin PMID set to 9V
//		vset[pmid,9,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x7F);  // Write reg 0xE = 127
I2CWriteSameData(DEV_ADDR, 0x56, 0x09);  // Write reg 0x56 = 9
I2CWriteSameData(DEV_ADDR, 0x57, 0x0E);  // Write reg 0x57 = 14
I2CWriteSameData(DEV_ADDR, 0x58, 0x05);  // Write reg 0x58 = 5
I2CWriteSameData(DEV_ADDR, 0x5E, 0x16);  // Write reg 0x5E = 22
//		field[(BUBO_MODE,0),(IBUS_SET,127),(EN_ATEST0,1),(ATEST0_MUX,22),(EN_ATEST1,1),(ATEST1_MUX,5),(DIS_NTC_DETECTION_ANALOG,1),(DMUX_EN,1),(DMUX_SEL,9)]
I2CWriteSameData(DEV_ADDR, 0x0D, 0x06);  // Write reg 0xD = 6
I2CWriteSameData(DEV_ADDR, 0x57, 0x0F);  // Write reg 0x57 = 15
I2CWriteSameData(DEV_ADDR, 0x59, 0x80);  // Write reg 0x59 = 128
//		field[(EN_I2C_CTRL,1),(D2A_BUBO_TM_DIS_VBATLOOP,1),(VBUS_VOL_SET_L,6)]
#10000;  // delay 1e-5s
//		delay[1e-5]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x59, 0xA0);  // Write reg 0x59 = 160
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]

`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 1e-3);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,1e-3,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(9, 1e-3);
#1000;
// pin PMID set to 9V
//		vset[pmid,9,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////