/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_LOOP_INDICTOR_BO ////////////
// Test Item: TM645, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5.1, 100e-6);
#1000;
// pin PMID set to 5.1V
//		vset[pmid,5.1,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]
`NVT_STIM.en_vsrc_sw = 1;
`NVT_STIM.vsrcSW.ramp_vsrc_val(3, 100e-6);
#1000;
// pin SW set to 3V
//		vset[sw,3,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x56, 0x08);  // Write reg 0x56 = 8
I2CWriteSameData(DEV_ADDR, 0x57, 0x0A);  // Write reg 0x57 = 10
I2CWriteSameData(DEV_ADDR, 0x5E, 0x18);  // Write reg 0x5E = 24
I2CWriteSameData(DEV_ADDR, 0x6F, 0xF60);  // Write reg 0x6F = 3936
//		field[(BUBO_MODE,1),(IBUS_SET,17),(EN_ATEST0,1),(ATEST0_MUX,24),(DIS_NTC_DETECTION_ANALOG,1),(DMUX_EN,1),(DMUX_SEL,8),(VBUS_VOL_SET_LIMIT,30)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x0B);  // Write reg 0x57 = 11
I2CWriteSameData(DEV_ADDR, 0x59, 0x80);  // Write reg 0x59 = 128
//		field[(EN_I2C_CTRL,1),(D2A_BUBO_TM_DIS_VBATLOOP,1)]
#10000;  // delay 1e-5s
//		delay[1e-5]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x59, 0xA0);  // Write reg 0x59 = 160
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.5, 100e-6);
#1000;
// pin VDM set to 1.5V
//		vset[vdm,1.5,100e-6,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]

`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.7, 10e-3);
#1000;
// pin VDM set to 1.7V
//		vset[vdm,1.7,10e-3,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1.5, 10e-3);
#1000;
// pin VDM set to 1.5V
//		vset[vdm,1.5,10e-3,0]
#10000000;  // delay 10e-3s
//		delay[10e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////