/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VBAT_LOOP_INDICTOR ////////////
// Test Item: TM643, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBAT set to 5V
//		vset[vbat,5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x0A, 0x41);  // Write reg 0xA = 65
I2CWriteSameData(DEV_ADDR, 0x0E, 0x39);  // Write reg 0xE = 57
I2CWriteSameData(DEV_ADDR, 0x56, 0x07);  // Write reg 0x56 = 7
I2CWriteSameData(DEV_ADDR, 0x57, 0x0C);  // Write reg 0x57 = 12
I2CWriteSameData(DEV_ADDR, 0x58, 0x03);  // Write reg 0x58 = 3
I2CWriteSameData(DEV_ADDR, 0x61, 0x53);  // Write reg 0x61 = 83
//		field[(BUBO_MODE,0),(VBAT_CV,1),(IBUS_SET,57),(VBUS_LOOP_DISABLE,1),(EN_ATEST1,1),(ATEST1_MUX,3),(DIS_NTC_DETECTION_ANALOG,1),(DMUX_EN,1),(DMUX_SEL,7)]
#10000;  // delay 1e-5s
//		delay[1e-5]
I2CWriteSameData(DEV_ADDR, 0x59, 0x20);  // Write reg 0x59 = 32
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]

#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3, 1e-3);
#1000;
// pin VBAT set to 3V
//		vset[vbat,3,1e-3,0]
`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(5, 1e-3);
#1000;
// pin VBAT set to 5V
//		vset[vbat,5,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////