/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BST UV/GD ////////////
// Test Item: TM641, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]
`NVT_STIM.en_vsrc_sw = 1;
`NVT_STIM.vsrcSW.ramp_vsrc_val(3, 100e-6);
#1000;
// pin SW set to 3V
//		vset[sw,3,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x0B);  // Write reg 0x56 = 11
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(DMUX_EN,1),(DMUX_SEL,11)]
#10000;  // delay 10e-6s
//		delay[10e-6]
I2CWriteSameData(DEV_ADDR, 0x59, 0x20);  // Write reg 0x59 = 32
//		field[(D2A_BUBO_TM_DIS_CLK,1)]

#100000;  // delay 100e-6s
//		delay[100e-6]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(2.5, 10e-3);
#1000;
// pin BST_SW set to 2.5V
//		vset[bst_sw,2.5,10e-3,0]
#100000;  // delay 100e-6s
//		delay[100e-6]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(4, 10e-3);
#1000;
// pin BST_SW set to 4V
//		vset[bst_sw,4,10e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////