/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: BOOST HS OCP ////////////
// Test Item: TM640, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.5, 100e-6);
#1000;
// pin VBAT set to 3.5V
//		vset[vbat,3.5,100e-6,0]
`NVT_STIM.en_vsrc_pmid = 1;
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,0]
`NVT_STIM.en_vsrc_bst_sw = 1;
`NVT_STIM.vsrcBST_SW.ramp_vsrc_val(5, 1e-3);
#1000;
// pin BST_SW set to 5V
//		vset[bst_sw,5,1e-3,0]
`NVT_STIM.en_vsrc_vdrv = 1;
`NVT_STIM.vsrcVDRV.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VDRV set to 5V
//		vset[vdrv,5,100e-6,0]
`NVT_STIM.en_vsrc_vdm = 1;
`NVT_STIM.vsrcVDM.ramp_vsrc_val(1, 100e-6);
#1000;
// pin VDM set to 1V
//		vset[vdm,1,100e-6,0]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x5A, 0x02);  // Write reg 0x5A = 2
//		field[(D2A_BUBO_TM_HSON,1),(BUBO_MODE,1),(D2A_BUBO_TM_LOW_ILIMT_OFF,1)]
I2CWriteSameData(DEV_ADDR, 0x67, 0x03);  // Write reg 0x67 = 3
//		field[(DIS_NTC_DETECTION_ANALOG,1),(D2A_OVRD_SEL,3)]
#50000;  // delay 5e-5s
//		delay[5e-5]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4B);  // Write reg 0x61 = 75
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
#10000;  // delay 1e-5s
//		delay[1e-5]
I2CWriteSameData(DEV_ADDR, 0x59, 0x20);  // Write reg 0x59 = 32
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x5A, 0x06);  // Write reg 0x5A = 6
//		field[(D2A_BUBO_TM_BOOST_OCP_EN,1)]
I2CWriteSameData(DEV_ADDR, 0x56, 0x25);  // Write reg 0x56 = 37
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
I2CWriteSameData(DEV_ADDR, 0x5F, 0x07);  // Write reg 0x5F = 7
//		field[(DMUX_EN,1),(DMUX_SEL,37),(D2A_BUBO_DTEST0,7)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_sw = 1;
`NVT_STIM.isrcSW.ramp_isrc_val(-2, 1e-3);
#1000;
// pin SW current set to -2A
//		iset[sw,-2,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x0A);  // Write reg 0x57 = 10
I2CWriteSameData(DEV_ADDR, 0x5B, 0x05);  // Write reg 0x5B = 5
//		field[(EN_ATEST0,1),(D2A_BUBO_ATEST0_MUX,5)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x61, 0x4F);  // Write reg 0x61 = 79
//		field[(BUBO_BOOST_OCP_OPT,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////