/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_REF ////////////
// Test Item: TM705, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,1]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x0B);  // Write reg 0xE = 11
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x61, 0x53);  // Write reg 0x61 = 83
//		field[(WAKE_UP,1),(BUBO_MODE,0),(IBAT_LIMIT,7),(IBUS_SET,11),(VBUS_LOOP_DISABLE,1)]

//		field[(DIS_NTC_DETECTION_ANALOG,1)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x04);  // Write reg 0x57 = 4
I2CWriteSameData(DEV_ADDR, 0x58, 0x07);  // Write reg 0x58 = 7
//		field[(EN_ATEST1,1),(ATEST1_MUX,7)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x06);  // Write reg 0x57 = 6
I2CWriteSameData(DEV_ADDR, 0x5E, 0x18);  // Write reg 0x5E = 24
//		field[(EN_ATEST0,1),(ATEST0_MUX,24)]
I2CWriteSameData(DEV_ADDR, 0x59, 0x04);  // Write reg 0x59 = 4
//		field[(D2A_BUBO_TM_DIS_BST_UVLO_LOCAL,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x07);  // Write reg 0x57 = 7
//		field[(EN_I2C_CTRL,1)]
I2CWriteSameData(DEV_ADDR, 0x61, 0x5B);  // Write reg 0x61 = 91
//		field[(D2A_BUBO_EN_FORCE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x59, 0x24);  // Write reg 0x59 = 36
//		field[(D2A_BUBO_TM_DIS_CLK,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]

#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x25);  // Write reg 0xE = 37
//		field[(IBUS_SET,37)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x0E, 0x4D);  // Write reg 0xE = 77
//		field[(IBUS_SET,77)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////