/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_SNS_ACC_BO ////////////
// Test Item: TM701, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.vsrcPMID.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_pmid = 1;
#1000;
// pin PMID set to 5V
//		vset[pmid,5,100e-6,1]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x57, 0x06);  // Write reg 0x57 = 6
I2CWriteSameData(DEV_ADDR, 0x58, 0x07);  // Write reg 0x58 = 7
I2CWriteSameData(DEV_ADDR, 0x5E, 0x19);  // Write reg 0x5E = 25
//		field[(WAKE_UP,1),(EN_ATEST0,1),(ATEST0_MUX,25),(EN_ATEST1,1),(ATEST1_MUX,7),(BUBO_MODE,1)]

`NVT_STIM.en_isrc_vbus = 1;
`NVT_STIM.isrcVBUS.ramp_isrc_val(1, 1e-3);
#1000;
// pin VBUS current set to 1A
//		iset[vbus,1,1e-3,0]
`NVT_STIM.en_isrc_vbus = 1;
`NVT_STIM.isrcVBUS.ramp_isrc_val(2, 1e-3);
#1000;
// pin VBUS current set to 2A
//		iset[vbus,2,1e-3,0]
`NVT_STIM.en_isrc_vbus = 1;
`NVT_STIM.isrcVBUS.ramp_isrc_val(0.5, 1e-3);
#1000;
// pin VBUS current set to 0.5A
//		iset[vbus,0.5,1e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////