/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_TERM ////////////
// Test Item: TM704, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_vbus = 1;
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,1]

entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x18);  // Write reg 0x56 = 24
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(WAKE_UP,1),(DMUX_EN,1),(DMUX_SEL,24)]
I2CWriteSameData(DEV_ADDR, 0x57, 0x09);  // Write reg 0x57 = 9
//		field[(en_i2c_ctrl,1)]
I2CWriteSameData(DEV_ADDR, 0xFB, 0x40);  // Write reg 0xFB = 64
//		field[(d2a_trim_opt_dis_term_flt,1)]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x07);  // Write reg 0xB = 7
//		field[(ITERM,7)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_pmid = 1;
`NVT_STIM.isrcPMID.ramp_isrc_val(1, 10e-3);
#1000;
// pin PMID current set to 1A
//		iset[pmid,1,10e-3,0]
`NVT_STIM.en_isrc_pmid = 1;
`NVT_STIM.isrcPMID.ramp_isrc_val(0, 10e-3);
#1000;
// pin PMID current set to 0A
//		iset[pmid,0,10e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x0B, 0x0F);  // Renew reg 0xB = 15
//		field_renew[(ITERM,15)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_pmid = 1;
`NVT_STIM.isrcPMID.ramp_isrc_val(1, 10e-3);
#1000;
// pin PMID current set to 1A
//		iset[pmid,1,10e-3,0]
`NVT_STIM.en_isrc_pmid = 1;
`NVT_STIM.isrcPMID.ramp_isrc_val(0, 10e-3);
#1000;
// pin PMID current set to 0A
//		iset[pmid,0,10e-3,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////