/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IAC_KLV2_VACWL_OCP ////////////
// Test Item: TM804, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.vsrcKLV1.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_klv1 = 1;
#1000;
// pin KLV1 set to 5V
//		vset[klv1,5,100e-6,1]
`NVT_STIM.vsrcKLV2.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_klv2 = 1;
#1000;
// pin KLV2 set to 5V
//		vset[klv2,5,100e-6,1]
`NVT_STIM.swKLV2_VACWL.set_ron_val(0.04);
`NVT_STIM.en_sw_klv2_vacwl = 1;
#1000000;
// pin KLV2_VACWL resistor = 0.04��
//		res[klv2_vacwl,0.04]

#1000000;  // delay 1e-3s
//		delay[1e-3]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x56, 0x3D);  // Write reg 0x56 = 61
I2CWriteSameData(DEV_ADDR, 0x57, 0x08);  // Write reg 0x57 = 8
//		field[(WAKE_UP,1),(DMUX_EN,1),(DMUX_SEL,61)]
#3000000;  // delay 3e-3s
//		delay[3e-3]
I2CWriteSameData(DEV_ADDR, 0x30, 0x10);  // Write reg 0x30 = 16
//		field[(IAC_SEL,4)]

//		field[(IAC_RATIO,0)]
I2CWriteSameData(DEV_ADDR, 0x24, 0x01);  // Write reg 0x24 = 1
//		field[(IAC_OCP,1)]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(2.6, 1e-3);
#1000;
// pin VAC_WL current set to 2.6A
//		iset[vac_wl,2.6,1e-3,0]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(0, 1e-3);
#1000;
// pin VAC_WL current set to 0A
//		iset[vac_wl,0,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x24, 0x02);  // Write reg 0x24 = 2
//		field[(IAC_OCP,2)]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(2.6, 1e-3);
#1000;
// pin VAC_WL current set to 2.6A
//		iset[vac_wl,2.6,1e-3,0]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(0, 1e-3);
#1000;
// pin VAC_WL current set to 0A
//		iset[vac_wl,0,1e-3,0]
I2CWriteSameData(DEV_ADDR, 0x24, 0x03);  // Write reg 0x24 = 3
//		field[(IAC_OCP,3)]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(2.6, 1e-3);
#1000;
// pin VAC_WL current set to 2.6A
//		iset[vac_wl,2.6,1e-3,0]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(0, 1e-3);
#1000;
// pin VAC_WL current set to 0A
//		iset[vac_wl,0,1e-3,0]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////