/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IAC_KLV2_VACWL_ACC ////////////
// Test Item: TM803, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.vsrcKLV2.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_klv2 = 1;
#1000;
// pin KLV2 set to 5V
//		vset[klv2,5,100e-6,1]
`NVT_STIM.vsrcKLV1.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_klv1 = 1;
#1000;
// pin KLV1 set to 5V
//		vset[klv1,5,100e-6,1]
`NVT_STIM.swKLV2_VACWL.set_ron_val(0.02);
`NVT_STIM.en_sw_klv2_vacwl = 1;
#1000000;
// pin KLV2_VACWL resistor = 0.02��
//		res[klv2_vacwl,0.02]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(1, 1e-3);
#1000;
// pin VAC_WL current set to 1A
//		iset[vac_wl,1,1e-3,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x18);  // Write reg 0x11 = 24
I2CWriteSameData(DEV_ADDR, 0x30, 0x10);  // Write reg 0x30 = 16
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,8),(EN_ATEST0,1),(ATEST0_MUX,31),(IAC_SEL,4)]

//		field[(IAC_RATIO,0)]
#1500000;  // delay 1.5e-3s
//		delay[1.5e-3]
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1E);  // Write reg 0x5E = 30
//		field[(ATEST0_MUX,30)]
#500000;  // delay 500e-6s
//		delay[500e-6]
`NVT_STIM.en_isrc_vac_wl = 1;
`NVT_STIM.isrcVAC_WL.ramp_isrc_val(2, 100e-6);
#1000;
// pin VAC_WL current set to 2A
//		iset[vac_wl,2,100e-6,0]
#500000;  // delay 500e-6s
//		delay[500e-6]
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(ATEST0_MUX,31)]
#500000;  // delay 500e-6s
//		delay[500e-6]
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1E);  // Write reg 0x5E = 30
//		field[(ATEST0_MUX,30)]
#500000;  // delay 500e-6s
//		delay[500e-6]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////