/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IAC_KLV1_VAC1_ACC ////////////
// Test Item: TM800, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4.4, 100e-6);
#1000;
// pin VBAT set to 4.4V
//		vset[vbat,4.4,100e-6,0]
`NVT_STIM.vsrcKLV1.ramp_vsrc_val(5, 100e-6);
`NVT_STIM.en_vsrc_klv1 = 1;
#1000;
// pin KLV1 set to 5V
//		vset[klv1,5,100e-6,1]
`NVT_STIM.swKLV1_VAC1.set_ron_val(0.02);
`NVT_STIM.en_sw_klv1_vac1 = 1;
#1000000;
// pin KLV1_VAC1 resistor = 0.02��
//		res[klv1_vac1,0.02]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_vac1 = 1;
`NVT_STIM.isrcVAC1.ramp_isrc_val(0.1, 1e-3);
#1000;
// pin VAC1 current set to 0.1A
//		iset[vac1,0.1,1e-3,0]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x18);  // Write reg 0x11 = 24
I2CWriteSameData(DEV_ADDR, 0x30, 0x04);  // Write reg 0x30 = 4
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,8),(EN_ATEST0,1),(ATEST0_MUX,31),(IAC_SEL,1)]
I2CWriteSameData(DEV_ADDR, 0x30, 0x07);  // Write reg 0x30 = 7
//		field[(IAC_RATIO,3)]
#500000;  // delay 500e-6s
//		delay[500e-6]
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1E);  // Write reg 0x5E = 30
//		field[(ATEST0_MUX,30)]
#500000;  // delay 500e-6s
//		delay[500e-6]
`NVT_STIM.en_isrc_vac1 = 1;
`NVT_STIM.isrcVAC1.ramp_isrc_val(0.5, 100e-6);
#1000;
// pin VAC1 current set to 0.5A
//		iset[vac1,0.5,100e-6,0]
#500000;  // delay 500e-6s
//		delay[500e-6]
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(ATEST0_MUX,31)]
#500000;  // delay 500e-6s
//		delay[500e-6]
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1E);  // Write reg 0x5E = 30
//		field[(ATEST0_MUX,30)]
#500000;  // delay 500e-6s
//		delay[500e-6]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////