/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: amux acc ////////////
// Test Item: TM901, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

`NVT_STIM.swAMUX.set_ron_val(200000);
`NVT_STIM.en_sw_amux = 1;
#1000000;
// pin AMUX resistor = 200000��
//		res[amux,200000]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,15)]
#3000000;  // delay 3e-3s
//		delay[3e-3]

I2CWriteSameData(DEV_ADDR, 0x11, 0x10);  // Write reg 0x11 = 16
//		field[(CHANNEL_MUX,0)]
#3000000;  // delay 3e-3s
//		delay[3e-3]
I2CWriteSameData(DEV_ADDR, 0x57, 0x02);  // Write reg 0x57 = 2
I2CWriteSameData(DEV_ADDR, 0x5E, 0x1F);  // Write reg 0x5E = 31
//		field[(EN_ATEST0,1),(ATEST0_MUX,31)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////