/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: IBUS_SML channel acc ////////////
// Test Item: TM908, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_vbus = 1;
`NVT_STIM.vsrcVBUS.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VBUS set to 5V
//		vset[vbus,5,100e-6,0]

`NVT_STIM.swAMUX.set_ron_val(200000);
`NVT_STIM.en_sw_amux = 1;
#1000000;
// pin AMUX resistor = 200000��
//		res[amux,200000]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,15)]
`NVT_STIM.en_isrc_pmid = 1;
`NVT_STIM.isrcPMID.ramp_isrc_val(0.4, 1e-3);
#1000;
// pin PMID current set to 0.4A
//		iset[pmid,0.4,1e-3,0]
#3000000;  // delay 3e-3s
//		delay[3e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x16);  // Write reg 0x11 = 22
//		field[(CHANNEL_MUX,6)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////