/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: vac2 channel acc ////////////
// Test Item: TM904, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(10, 100e-6);
#1000;
// pin VAC2 set to 10V
//		vset[vac2,10,100e-6,0]

`NVT_STIM.swAMUX.set_ron_val(200000);
`NVT_STIM.en_sw_amux = 1;
#1000000;
// pin AMUX resistor = 200000��
//		res[amux,200000]
entertestmode();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(WAKE_UP,1),(AMUX_EN,1),(CHANNEL_MUX,15)]
#3000000;  // delay 3e-3s
//		delay[3e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x12);  // Write reg 0x11 = 18
//		field[(CHANNEL_MUX,2)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////