/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: AMUX IQ ////////////
// Test Item: TM913, generate time: 2026-05-15 16:48:30 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]

wait_warmup();
//		wait_warmup[]
`NVT_STIM.swAMUX.set_ron_val(200000);
`NVT_STIM.en_sw_amux = 1;
#1000000;
// pin AMUX resistor = 200000¦¸
//		res[amux,200000]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(WAKE_UP,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x11, 0x1F);  // Write reg 0x11 = 31
//		field[(AMUX_EN,1),(CHANNEL_MUX,15)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////