/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: manual_Q ////////////
// Test Item: TX_501, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x28, 0x02);  // Write reg 0x28 = 2
//		field[(Q_MANUAL_EN,1)]
#1000000000;  // delay 1000e-3s
//		delay[1000e-3]
I2CWriteSameData(DEV_ADDR, 0x28, 0x00);  // Write reg 0x28 = 0
//		field[(Q_MANUAL_EN,0)]
I2CWriteSameData(DEV_ADDR, 0x27, 0x30);  // Write reg 0x27 = 48
I2CWriteSameData(DEV_ADDR, 0x28, 0x0C);  // Write reg 0x28 = 12
//		field[(Q_DET_RATIO,3),(Q_PRE_CHG_VOL,3)]
I2CWriteSameData(DEV_ADDR, 0x28, 0x0E);  // Write reg 0x28 = 14
//		field[(Q_MANUAL_EN,1)]
#1000000000;  // delay 1000e-3s
//		delay[1000e-3]
$finish;
//		finish[]

// Error: command format error: nan
//		nan

// Error: command format error: nan
//		nan

/////////////////////// End of Auto-generated Code ////////////