/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TX_NO_PWM ////////////
// Test Item: TX_504, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2500000;  // delay 2.5e-3s
//		delay[2.5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(ac1_gate_on,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x23, 0x04);  // Write reg 0x23 = 4
I2CWriteSameData(DEV_ADDR, 0x31, 0x00);  // Write reg 0x31 = 0
//		field[(powerstage_en,1),(wl_drv_deadtime,0)]

#10000000;  // delay 10e-3s
//		delay[10e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////