/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TX_INPUT_OV ////////////
// Test Item: TX_506, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2500000;  // delay 2.5e-3s
//		delay[2.5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(ac1_gate_on,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x23, 0x04);  // Write reg 0x23 = 4
I2CWriteSameData(DEV_ADDR, 0x31, 0x40);  // Write reg 0x31 = 64
//		field[(powerstage_en,1),(wl_drv_deadtime,1)]

#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.reg_en_pwm = 1;
//		pwm_en[1]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 1562;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 20.0% duty, 0.0% shift
//		pwm_set[128e3,20,0,1]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(9, 100e-6);
#1000;
// pin VAC1 set to 9V
//		vset[vac1,9,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////