/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: auto_Q ////////////
// Test Item: TX_500, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x28, 0x02);  // Write reg 0x28 = 2
//		field[(Q_MANUAL_EN,1)]
#20000000;  // delay 20e-3s
//		delay[20e-3]
I2CWriteSameData(DEV_ADDR, 0x28, 0x01);  // Renew reg 0x28 = 1
//		field_renew[(Q_AUTO_EN,1)]
#1500000000;  // delay 1500e-3s
//		delay[1500e-3]
I2CWriteSameData(DEV_ADDR, 0x27, 0x10);  // Write reg 0x27 = 16
I2CWriteSameData(DEV_ADDR, 0x28, 0x05);  // Write reg 0x28 = 5
//		field[(Q_DET_RATIO,1),(Q_PRE_CHG_VOL,1)]
#1000000000;  // delay 1000e-3s
//		delay[1000e-3]
$finish;
//		finish[]

// Error: command format error: nan
//		nan

// Error: command format error: nan
//		nan

/////////////////////// End of Auto-generated Code ////////////