/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: TX_BPP ////////////
// Test Item: TX_502, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x0C);  // Write reg 0xFF = 12
//		field[(mpp_en,1),(rx_mode_en,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,100e-6,0]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2500000;  // delay 2.5e-3s
//		delay[2.5e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(ac1_gate_on,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x0C);  // Write reg 0xC = 12
I2CWriteSameData(DEV_ADDR, 0x23, 0x04);  // Write reg 0x23 = 4
I2CWriteSameData(DEV_ADDR, 0x31, 0x40);  // Write reg 0x31 = 64
//		field[(powerstage_en,1),(wl_drv_deadtime,1),(vbus_ovp,3)]
I2CWriteSameData(DEV_ADDR, 0x24, 0xF8);  // Write reg 0x24 = 248
//		field[(tx_ocp,7),(tx_ocp_deg,3)]
I2CWriteSameData(DEV_ADDR, 0x25, 0x3F);  // Write reg 0x25 = 63
//		field[(sel_dma,3),(sel_dmo,3)] // 4 round add
I2CWriteSameData(DEV_ADDR, 0x30, 0x10);  // Write reg 0x30 = 16
//		field[(iac_en,1),(iac_sel,4)] // 4 round add
I2CWriteSameData(DEV_ADDR, 0x26, 0x04);  // Write reg 0x26 = 4
//		field[(VCAP_RATIO,4)] // 5 round add, gain=1
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.reg_en_pwm = 1;
//		pwm_en[1]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 781;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 10.0% duty, 0.0% shift
//		pwm_set[128e3,10,0,1]

#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x23, 0x05);  // Write reg 0x23 = 5
//		field[(drvh_en,1)]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 3124;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 40.0% duty, 0.0% shift
//		pwm_set[128e3,40,0,1]
#1000000;  // delay 1e-3s
//		delay[1e-3]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 3906;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 50.0% duty, 0.0% shift
//		pwm_set[128e3,50,0,1]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(9, 100e-6);
#1000;
// pin VAC1 set to 9V
//		vset[vac1,9,100e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]

`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.07, 1e-6);
#1000;
// pin VRECT current set to 1.07A
//		iset[vrect,1.07,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.en_isrc_vrect = 1;
`NVT_STIM.isrcVRECT.ramp_isrc_val(1.0, 1e-6);
#1000;
// pin VRECT current set to 1.0A
//		iset[vrect,1.0,1e-6,0]
#512000;  // delay 512e-6s
//		delay[512e-6]
`NVT_STIM.swVRECT.set_ron_val(0.01);
`NVT_STIM.en_sw_vrect = 1;
#1000000;
// pin VRECT resistor = 0.01¦¸
//		res[vrect,0.01]
#500000;  // delay 0.5e-3s
//		delay[0.5e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////