/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC_SNK_LargeCap ////////////
// Test Item: USB_110, generate time: 2026-05-06 19:03:47 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_UVM_TOP.i_iic.write_byte(`DEV_ADDR, 8'h10, 8'h43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#3000000;  // delay 3e-3s
//		delay[3e-3]
`NVT_UVM_TOP.i_iic.write_byte(`DEV_ADDR, 8'h1, 8'h8);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
`NVT_UVM_TOP.i_iic.write_byte(`DEV_ADDR, 8'h9, 8'hE);  // Write reg 0x9 = 14
`NVT_UVM_TOP.i_iic.write_byte(`DEV_ADDR, 8'hD, 8'h1E);  // Write reg 0xD = 30
//		field[(BUBO_EN,1),(BUBO_MODE,1),(VBUS_VOL_SET_L,30)]
#4000000;  // delay 4e-3s
//		delay[4e-3]

`NVT_STIM.swVAC1.set_ron_val(10);
`NVT_STIM.en_sw_vac1 = 1;
#1000000;
// pin VAC1 resistor = 10¦¸
//		res[vac1,10]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_UVM_TOP.i_iic.write_byte(`DEV_ADDR, 8'h8, 8'h4);  // Write reg 0x8 = 4
//		field[(AC1_GATE_ON,1)]
#4000000;  // delay 4e-3s
//		delay[4e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////