/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC_SRC_HIGH ////////////
// Test Item: USB_106, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x01, 0x08);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(12, 100e-6);
#1000;
// pin VAC2 set to 12V
//		vset[vac2,12,100e-6,0]
#100000;  // delay 0.1e-3s
//		delay[0.1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
I2CWriteSameData(DEV_ADDR, 0x0C, 0x08);  // Write reg 0xC = 8
//		field[(VBUS_OVP,2),(AC2_GATE_ON,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(24, 12e-6);
#1000;
// pin VAC2 set to 24V
//		vset[vac2,24,12e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x0A);  // Write reg 0x8 = 10
//		field[(VBUS_PULLDOWN,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////