/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC_SNK_REL_2 ////////////
// Test Item: USB_108, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#8000000;  // delay 8e-3s
//		delay[8e-3]
I2CWriteSameData(DEV_ADDR, 0x01, 0x08);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
I2CWriteSameData(DEV_ADDR, 0x07, 0x07);  // Write reg 0x7 = 7
//		field[(VAC2_APORT_DET_Enable,1),(VAC1_APORT_DET_Enable,1),(VAC_SNK_DET_SEL,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0C, 0x04);  // Write reg 0xC = 4
I2CWriteSameData(DEV_ADDR, 0x0D, 0xE6);  // Write reg 0xD = 230
//		field[(VBUS_OVP,1),(BUBO_EN,1),(BUBO_MODE,1),(VBUS_VOL_SET_L,230),]
en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0x60, 0x10);  // Write reg 0x60 = 16
//		field[(AC2_GATE_SS_EN,1)]
#5000000;  // delay 5e-3s
//		delay[5e-3]

`NVT_STIM.swVAC2.set_ron_val(10);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 10¦¸
//		res[vac2,10]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac2_cable_insert = 0;  // plugout vac2
//		plugout[vac2]
#5000000;  // delay 5e-3s
//		delay[5e-3]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0A);  // Write reg 0x9 = 10
//		field[(BUBO_EN,0)]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x00);  // Write reg 0x8 = 0
//		field[(AC2_GATE_ON,0)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.swVAC1.set_ron_val(10);
`NVT_STIM.en_sw_vac1 = 1;
#1000000;
// pin VAC1 resistor = 10¦¸
//		res[vac1,10]
`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
#3000000;  // delay 3e-3s
//		delay[3e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////