/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC3_PLUG_IN_OUT ////////////
// Test Item: USB_102, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x01, 0x08);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
I2CWriteSameData(DEV_ADDR, 0x07, 0x06);  // Write reg 0x7 = 6
//		field[(VAC1_APORT_DET_Enable,1),(VAC2_APORT_DET_Enable,1)]

`NVT_STIM.en_vac3_cable_insert = 1;  // plugin vac3
//		plugin[vac3]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(5, 0.5e-6);
#1000;
// pin VAC3 set to 5V
//		vset[vac3,5,0.5e-6,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x01);  // Write reg 0x8 = 1
//		field[(AC3_GATE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x09);  // Write reg 0x8 = 9
//		field[(VBUS_PULLDOWN,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x19);  // Write reg 0x8 = 25
//		field[(VAC3_PULLDOWN,1)]
I2CWriteSameData(DEV_ADDR, 0x0C, 0x0C);  // Write reg 0xC = 12
//		field[(VBUS_OVP,3)]  //
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(15, 0.7e-6);
#1000;
// pin VAC3 set to 15V
//		vset[vac3,15,0.7e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(24, 0.7e-6);
#1000;
// pin VAC3 set to 24V
//		vset[vac3,24,0.7e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac3_cable_insert = 0;  // plugout vac3
//		plugout[vac3]
#1000000;  // delay 1e-3s
//		delay[1e-3]

#50000000;  // delay 50e-3s
//		delay[50e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////