/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC_SRC_MUTI ////////////
// Test Item: USB_105, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
I2CWriteSameData(DEV_ADDR, 0x01, 0x08);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
`NVT_STIM.en_vsrc_vac2 = 1;
`NVT_STIM.vsrcVAC2.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VAC2 set to 5V
//		vset[vac2,5,100e-6,0]
#100000;  // delay 0.1e-3s
//		delay[0.1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]

`NVT_STIM.en_vsrc_vac3 = 1;
`NVT_STIM.vsrcVAC3.ramp_vsrc_val(6, 100e-6);
#1000;
// pin VAC3 set to 6V
//		vset[vac3,6,100e-6,0]
`NVT_STIM.en_vac3_cable_insert = 1;  // plugin vac3
//		plugin[vac3]
#10000000;  // delay 10e-3s
//		delay[10e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////