/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC1_PLUG_IN_OUT ////////////
// Test Item: USB_100, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(3.7, 100e-6);
#1000;
// pin VBAT set to 3.7V
//		vset[vbat,3.7,100e-6,0]
wait_warmup();
//		wait_warmup[]
I2CWriteSameData(DEV_ADDR, 0x01, 0x08);  // Write reg 0x1 = 8
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_LOOP_INT_MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
I2CWriteSameData(DEV_ADDR, 0x07, 0x06);  // Write reg 0x7 = 6
//		field[(VAC1_APORT_DET_Enable,1),(VAC2_APORT_DET_Enable,1)]

`NVT_STIM.en_vac1_cable_insert = 1;  // plugin vac1
//		plugin[vac1]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(5, 0.5e-6);
#1000;
// pin VAC1 set to 5V
//		vset[vac1,5,0.5e-6,0]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x04);  // Write reg 0x8 = 4
//		field[(AC1_GATE_ON,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x0C);  // Write reg 0x8 = 12
//		field[(VBUS_PULLDOWN,1)]
I2CWriteSameData(DEV_ADDR, 0x08, 0x4C);  // Write reg 0x8 = 76
//		field[(VAC1_PULLDOWN,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
`NVT_STIM.en_vsrc_vac1 = 1;
`NVT_STIM.vsrcVAC1.ramp_vsrc_val(12, 0.7e-6);
#1000;
// pin VAC1 set to 12V
//		vset[vac1,12,0.7e-6,0]
#1000000;  // delay 1e-3s
//		delay[1e-3]
`NVT_STIM.en_vac1_cable_insert = 0;  // plugout vac1
//		plugout[vac1]
#1000000;  // delay 1e-3s
//		delay[1e-3]

#50000000;  // delay 50e-3s
//		delay[50e-3]
$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////