/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: RX_PING_DEADBAT ////////////
// Test Item: USB_104, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vrect = 1;
`NVT_STIM.vsrcVRECT.ramp_vsrc_val(5, 100e-6);
#1000;
// pin VRECT set to 5V
//		vset[vrect,5,100e-6,0]
`NVT_STIM.reg_en_tx = 1;  // en_reg tx, 1
//		en_reg[tx,1]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 781;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 10.0% duty, 0.0% shift
//		pwm_set[128e3,10,0,1]
#100000;  // delay 0.1e-3s
//		delay[0.1e-3]
tb.Ipwm.cyc = 7812;
tb.Ipwm.duty = 2343;
tb.Ipwm.shift = 3906;
tb.Ipwm.en = 1;
#1000;
// PWM: 128000.0Hz, 30.0% duty, 0.0% shift
//		pwm_set[128e3,30,0,1]
#200000;  // delay 0.2e-3s
//		delay[0.2e-3]
wait_warmup();
//		wait_warmup[]

en_tm();
//		en_tm[]
I2CWriteSameData(DEV_ADDR, 0xFF, 0x08);  // Write reg 0xFF = 8
//		field[(rx_mode_en,1)] // enable rx function
`NVT_STIM.reg_en_mcu_load = 1;  // en_reg mcu_load, 1
//		en_reg[mcu_load,1]
#200000;  // delay 0.2e-3s
//		delay[0.2e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x08);  // Write reg 0x8 = 8
I2CWriteSameData(DEV_ADDR, 0x0C, 0x08);  // Write reg 0xC = 8
//		field[(VBUS_OVP,2),(VBUS_PULLDOWN,1)] // VBUS OVP 13V
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)] // wake up
I2CWriteSameData(DEV_ADDR, 0x32, 0x04);  // Write reg 0x32 = 4
//		field[(FSK_ALLOW,1)] // allow fsk in rx mode
I2CWriteSameData(DEV_ADDR, 0x23, 0x02);  // Write reg 0x23 = 2
//		field[(POWERSTAGE_MODE,1)] // rx mode
I2CWriteSameData(DEV_ADDR, 0x23, 0x06);  // Write reg 0x23 = 6
//		field[(POWERSTAGE_EN,1)] // enable RX
#8000000;  // delay 8e-3s
//		delay[8e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////