/////////////////////// Auto-generated AMS Test Code ////////////
/////////////////////// Test: VAC_SNK_REL_1 ////////////
// Test Item: USB_107, generate time: 2026-07-01 10:32:31 //
//////////////////generated by Tom/////////////////////////////

`NVT_STIM.en_vsrc_vbat = 1;
`NVT_STIM.vsrcVBAT.ramp_vsrc_val(4, 100e-6);
#1000;
// pin VBAT set to 4V
//		vset[vbat,4,100e-6,0]
wait_warmup();
//		wait_warmup[]
#2000000;  // delay 2e-3s
//		delay[2e-3]
I2CWriteSameData(DEV_ADDR, 0x10, 0x43);  // Write reg 0x10 = 67
//		field[(wake_up,1)]
#10000000;  // delay 10e-3s
//		delay[10e-3]
I2CWriteSameData(DEV_ADDR, 0x01, 0x40);  // Write reg 0x1 = 64
//		field[(VBUS_PRESENT_INT_MASK,0),(BUBO_FAULT_INT MASK,0),(VAC2_SNK_DET_INT_MASK,0),(VAC1_SNK_DET_INT_MASK,0),(BUBO_FAULT_INT_MASK,0),(TEMP_FAULT_INT_MASK,0),(CHG_FSM_INT_MASK,0)]
I2CWriteSameData(DEV_ADDR, 0x07, 0x05);  // Write reg 0x7 = 5
//		field[(VAC2_APORT_DET_Enable,1),(VAC_SNK_DET_SEL,1)]
I2CWriteSameData(DEV_ADDR, 0x09, 0x0E);  // Write reg 0x9 = 14
I2CWriteSameData(DEV_ADDR, 0x0D, 0x1E);  // Write reg 0xD = 30
//		field[(BUBO_EN,1),(BUBO_MODE,1),(VBUS_VOL_SET_L,30)]
#5000000;  // delay 5e-3s
//		delay[5e-3]

`NVT_STIM.swVAC2.set_ron_val(10);
`NVT_STIM.en_sw_vac2 = 1;
#1000000;
// pin VAC2 resistor = 10¦¸
//		res[vac2,10]
`NVT_STIM.en_vac2_cable_insert = 1;  // plugin vac2
//		plugin[vac2]
#1000000;  // delay 1e-3s
//		delay[1e-3]
I2CWriteSameData(DEV_ADDR, 0x08, 0x02);  // Write reg 0x8 = 2
//		field[(AC2_GATE_ON,1)]
#4000000;  // delay 4e-3s
//		delay[4e-3]

$finish;
//		finish[]

/////////////////////// End of Auto-generated Code ////////////